import { ArrowRight, Building2, Factory, Globe2, History, ShieldCheck, Users } from "lucide-react";
import { Link } from "wouter";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";

const milestones = [
  { period: "1919", title: "Uma origem ligada à inovação", text: "A Cummins informa que foi fundada em 3 de fevereiro de 1919, em Columbus, Indiana, por Clessie Cummins com William G. Irwin. O primeiro motor foi produzido naquele mesmo ano.", source: "https://investor.cummins.com/company-info/faq", icon: History },
  { period: "1924–1930", title: "Motores e novas aplicações", text: "A cronologia institucional registra a evolução dos motores Model F e Model U e a ampliação do uso automotivo da tecnologia Cummins.", source: "https://www.cummins.com/en-na/news/history-diesel-engines", icon: Factory },
  { period: "1956", title: "Presença internacional", text: "A história oficial registra a abertura da primeira unidade estrangeira de fabricação da empresa em Shotts, na Escócia.", source: "https://www.cummins.com/en-na/news/history-diesel-engines", icon: Globe2 },
  { period: "1971", title: "A Cummins no Brasil", text: "A Cummins Brasil informa que sua subsidiária foi constituída oficialmente em 1971, em Guarulhos, iniciando uma trajetória industrial e de serviços no país.", source: "https://www.cummins.com/pt-br/br/quem-somos/nossa-historia", icon: Building2 },
  { period: "2022", title: "Integração com a Meritor", text: "A Cummins concluiu a aquisição global da Meritor em agosto de 2022, reunindo competências em drivetrain, frenagem, mobilidade e tecnologias para veículos comerciais.", source: "https://www.cummins.com/news/releases/2022/08/03/cummins-completes-acquisition-meritor", icon: Users },
  { period: "Hoje", title: "Pessoas, tecnologia e responsabilidade", text: "A Cummins apresenta seus negócios em motores, sistemas de potência, componentes, distribuição e Accelera. Em Osasco, documentos corporativos identificam operações CDBS e duas fábricas, sem divulgar aqui detalhes operacionais não autorizados.", source: "https://www.cummins.com/en-na/company/esg/social/diversity/pay-balance", icon: ShieldCheck },
];

export default function HistoriaCummins() {
  return (
    <div className="min-h-screen bg-[#0d0f13] text-slate-100"><Navbar /><main>
      <section className="border-b border-white/10 bg-gradient-to-b from-[#161a24] to-[#0d0f13] px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="v2-kicker flex items-center gap-2"><History className="h-4 w-4 text-[#da291c]" aria-hidden="true" /> Conteúdo institucional permanente</div><h1 className="mt-4 max-w-4xl font-industrial text-5xl uppercase leading-[.95] text-white sm:text-8xl">A história da <span className="text-[#da291c]">Cummins.</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-slate-200">Uma trajetória de inovação em motores e tecnologias de energia, construída por pessoas e conectada a diferentes comunidades, mercados e possibilidades para o futuro.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="bg-[#da291c] font-bold uppercase text-white hover:bg-[#b01e12]"><Link href="/sobre">Conhecer Osasco <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="border-white/20 text-white hover:bg-white/10"><a href="https://www.cummins.com/en-na/company" target="_blank" rel="noreferrer">Fonte institucional Cummins</a></Button></div></div></section>

      <section className="border-b border-white/10 bg-[#12151d] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><div className="mb-10 max-w-3xl"><div className="v2-kicker">Linha do tempo</div><h2 className="mt-2 font-industrial text-4xl uppercase text-white">Marcos e continuidade</h2><p className="mt-4 text-sm leading-relaxed text-slate-300">A linha do tempo resume informações publicadas pela própria Cummins. Datas, descrições e escopo devem ser revisados com a equipe responsável antes de usos institucionais formais.</p></div><div className="relative space-y-4 before:absolute before:bottom-0 before:left-[19px] before:top-0 before:w-px before:bg-red-500/40 sm:before:left-[27px]">{milestones.map((item) => <article key={item.period} className="relative grid gap-4 rounded-2xl border border-white/10 bg-[#141822] p-5 pl-14 sm:grid-cols-[9rem_1fr] sm:pl-20"><div className="absolute left-3 top-6 flex h-3.5 w-3.5 rounded-full border-2 border-[#0d0f13] bg-[#da291c] sm:left-5" aria-hidden="true" /><div className="font-industrial text-3xl text-[#da291c] sm:text-4xl">{item.period}</div><div><div className="flex items-start gap-3"><item.icon className="mt-1 h-5 w-5 shrink-0 text-amber-300" aria-hidden="true" /><h3 className="font-industrial text-xl uppercase text-white">{item.title}</h3></div><p className="mt-3 text-sm leading-relaxed text-slate-300">{item.text}</p><a href={item.source} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center text-xs font-bold text-amber-300 hover:text-white">Ver fonte <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></a></div></article>)}</div></div></section>

      <section className="border-b border-white/10 bg-[#0f1218] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-3"><article className="rounded-2xl border border-white/10 bg-[#141822] p-6"><Building2 className="h-8 w-8 text-[#da291c]" aria-hidden="true" /><h2 className="mt-6 font-industrial text-2xl uppercase text-white">No Brasil</h2><p className="mt-3 text-sm leading-relaxed text-slate-400">A operação brasileira reúne fabricação, distribuição, serviços e soluções de energia e componentes, conforme as páginas institucionais da Cummins.</p></article><article className="rounded-2xl border border-white/10 bg-[#141822] p-6"><Factory className="h-8 w-8 text-amber-300" aria-hidden="true" /><h2 className="mt-6 font-industrial text-2xl uppercase text-white">Em Osasco</h2><p className="mt-3 text-sm leading-relaxed text-slate-400">A documentação corporativa identifica a operação CDBS em Osasco. Informações de produção, capacidade, equipes e processos internos não são apresentadas sem autorização oficial.</p></article><article className="rounded-2xl border border-white/10 bg-[#141822] p-6"><ShieldCheck className="h-8 w-8 text-emerald-300" aria-hidden="true" /><h2 className="mt-6 font-industrial text-2xl uppercase text-white">Pessoas e futuro</h2><p className="mt-3 text-sm leading-relaxed text-slate-400">A história também é feita por formação profissional, voluntariado, segurança, inovação e responsabilidade nas comunidades onde a empresa atua.</p></article></div></section>
      <section className="px-4 py-10 text-center sm:px-6 lg:px-8"><p className="mx-auto max-w-3xl text-xs leading-relaxed text-slate-500">Fontes principais: Cummins global, Cummins Brasil, relações com investidores e documentos institucionais. A página não substitui validação oficial da empresa.</p></section>
    </main></div>
  );
}
