import { ArrowRight, Code2, ExternalLink, Gamepad2, GraduationCap, HeartHandshake, Linkedin, Mail, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Link } from "wouter";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { REAL_PHOTOS } from "@/data/realPhotos";
import { InstitutionalGallery } from "@/components/InstitutionalGallery";
import { ProjectTimeline } from "@/components/ProjectTimeline";

const pillars = [
  { icon: Gamepad2, title: "Jogos e desafios", text: "Desafios transformam conceitos de segurança, ergonomia e prevenção em decisões práticas e interativas." },
  { icon: GraduationCap, title: "Aprendizado aplicado", text: "Quizzes, explicações e feedback conectam conhecimento com atitudes do dia a dia no trabalho." },
  { icon: ShieldCheck, title: "Segurança e ergonomia", text: "A experiência aborda percepção de riscos, ergonomia, comunicação e melhoria contínua." },
  { icon: Code2, title: "Tecnologia com propósito", text: "A plataforma usa tecnologia, comunicação e criatividade para aproximar a SIPAT das pessoas." },
];

const creators = [
  { name: "Ryan Neiva", role: "Idealização e desenvolvimento", email: "ryanneiva80@gmail.com", linkedin: "https://www.linkedin.com/in/ryan-neiva" },
  { name: "Leonardo Frazatto", role: "Idealização e desenvolvimento", email: "lmpfrazatto@gmail.com", linkedin: "https://www.linkedin.com/in/leonardo-machado-pereira-fraza" },
  { name: "Matheus Felipe", role: "Idealização e desenvolvimento", email: "matheusfelipedasferreira@gmail.com" },
];

const process = [
  ["01", "Escutar e entender", "Partimos da necessidade de tornar a SIPAT mais interativa, clara e próxima da realidade dos colaboradores."],
  ["02", "Pesquisar e organizar", "Relacionamos segurança, saúde, ergonomia, prevenção, 5S e Lean em uma arquitetura simples de navegar."],
  ["03", "Criar e testar", "Desenvolvemos jogos, feedbacks, ranking, progresso e alternativas acessíveis para diferentes formas de participação."],
  ["04", "Aprender fazendo", "A construção reuniu colaboração, criatividade, comunicação e conhecimentos desenvolvidos durante o Formare."],
];

export default function NossoProjeto() {
  return <div className="min-h-screen bg-[#0d0f13] text-slate-100"><Navbar /><main>
    <section className="border-b border-white/10 bg-gradient-to-b from-[#161a24] to-[#0d0f13] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="v2-kicker">SIPAT CUMMINS OSASCO / PROJETO FORMare</div><h1 className="mt-3 font-industrial text-5xl uppercase leading-none text-white sm:text-8xl">Nosso<br /><span className="text-[#da291c]">projeto.</span></h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-200">Uma plataforma educativa criada para aproximar pessoas, conhecimento e segurança na SIPAT Cummins Osasco.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="bg-[#da291c] font-bold uppercase text-white hover:bg-[#b01e12]"><Link href="/jogos">Conhecer os desafios <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="border-white/20 text-white hover:bg-white/10"><Link href="/formare">Conhecer o Formare</Link></Button></div></div></section>

    <section id="somos-do-formare" className="scroll-mt-20 border-b border-white/10 bg-gradient-to-r from-red-950/40 via-[#151922] to-[#12151d] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><div className="v2-kicker flex items-center gap-2"><HeartHandshake className="h-4 w-4 text-amber-300" aria-hidden="true" /> Identidade do projeto</div><h2 className="mt-2 font-industrial text-5xl uppercase text-white sm:text-7xl">Somos do <span className="text-amber-300">Formare.</span></h2><p className="mt-6 text-lg leading-relaxed text-slate-200">Somos alunos do Formare e desenvolvemos este projeto para a SIPAT Cummins Osasco.</p><p className="mt-4 max-w-3xl text-sm leading-relaxed text-slate-300">O Formare oferece formação profissional, desenvolvimento pessoal e preparação para o mundo do trabalho. Para nós, essa experiência significa ampliar conhecimentos, desenvolver novas habilidades e construir novas possibilidades para o futuro, em contato com pessoas, áreas e rotinas de uma grande empresa.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{pillars.map((item) => <article key={item.title} className="rounded-2xl border border-white/10 bg-black/25 p-5 transition hover:-translate-y-1 hover:border-amber-300/50"><item.icon className="h-7 w-7 text-amber-300" aria-hidden="true" /><h3 className="mt-5 font-industrial text-xl uppercase text-white">{item.title}</h3><p className="mt-2 text-xs leading-relaxed text-slate-400">{item.text}</p></article>)}</div><Link href="/formare" className="mt-8 inline-flex min-h-11 items-center text-xs font-bold uppercase text-amber-300 hover:text-white">Leia sobre o impacto do Formare <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section>

    <section className="border-b border-white/10 bg-[#0f1218] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><div className="v2-kicker">Uma oportunidade que transforma futuros</div><h2 className="mt-2 font-industrial text-4xl uppercase text-white">Educação, segurança e futuro</h2><p className="mt-5 text-sm leading-relaxed text-slate-300">O Formare pode ajudar jovens a acreditar mais em seu potencial, desenvolver autonomia, aprender a trabalhar em equipe, melhorar a comunicação, conhecer possibilidades de carreira e ampliar seus objetivos. Não é uma promessa de resultado igual para todos: é uma oportunidade concreta de aprendizagem e crescimento.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Potencial e autonomia", "Responsabilidade e colaboração", "Comunicação e organização", "Novas áreas profissionais", "Experiências para o futuro", "Possibilidades por meio da educação"].map((text, index) => <div key={text} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#141822] p-4"><span className="font-mono text-xs text-[#da291c]">0{index + 1}</span><span className="text-sm text-slate-200">{text}</span></div>)}</div></div></section>

    <section className="border-b border-white/10 bg-[#12151d] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><div className="v2-kicker">Depois do contexto, a equipe</div><h2 className="mt-2 font-industrial text-4xl uppercase text-white">Alunos do Formare em ação</h2><p className="mt-4 text-sm leading-relaxed text-slate-300">Agora que você conhece o programa e o contexto da nossa formação, apresentamos a equipe responsável pelo desenvolvimento deste projeto.</p></div><figure className="group mt-8 overflow-hidden rounded-2xl border border-white/15 bg-[#141822] shadow-2xl shadow-black/50"><div className="relative aspect-video w-full overflow-hidden bg-black/40"><img src={REAL_PHOTOS.team.src} alt="Alunos do Formare reunidos em uma sala diante de uma lousa, celebrando o desenvolvimento do projeto SIPAT Cummins Osasco" width="1280" height="720" loading="lazy" decoding="async" className="h-full w-full object-cover object-[center_35%] transition duration-300 group-hover:scale-[1.02]" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><div className="absolute bottom-3 left-3 rounded-md border border-white/10 bg-black/70 px-2.5 py-1 text-[11px] font-medium text-white backdrop-blur-md">Alunos do Formare • Cummins Osasco</div></div><figcaption className="border-t border-white/10 bg-[#141822] px-4 py-4 text-xs leading-relaxed text-slate-300"><span className="font-semibold text-white">Alunos do Formare responsáveis pelo desenvolvimento do projeto SIPAT Cummins Osasco.</span><br />Imagem enviada pela equipe do projeto. Confirme a autorização de uso de imagem conforme as regras da organização antes de divulgação externa.</figcaption></figure></div></section>

    <section className="border-b border-white/10 bg-[#0f1218] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="v2-kicker">Nosso projeto para a SIPAT Cummins Osasco</div><h2 className="mt-2 font-industrial text-4xl uppercase text-white">Como alunos do Formare, criamos uma experiência real</h2><p className="mt-5 max-w-4xl text-sm leading-relaxed text-slate-300">Como alunos do Formare, desenvolvemos esta plataforma para tornar a experiência da SIPAT mais interativa, educativa e próxima da realidade dos colaboradores. Unimos tecnologia, comunicação, criatividade e conhecimentos de segurança para criar uma experiência com quatro desafios, ranking e conteúdos de prevenção.</p><ProjectTimeline /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{process.map(([number, title, text]) => <article key={number} className="rounded-xl border border-white/10 bg-[#141822] p-5"><span className="font-mono text-sm font-bold text-[#da291c]">{number}</span><h3 className="mt-5 font-industrial text-xl uppercase text-white">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{text}</p></article>)}</div></div></section>

    <section className="border-b border-white/10 bg-[#12151d] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><div className="v2-kicker">Resultado e propósito</div><h2 className="mt-2 font-industrial text-4xl uppercase text-white">Aprender para cuidar melhor</h2><p className="mt-5 text-sm leading-relaxed text-slate-300">O projeto reúne formação dos jovens pelo Formare, compromisso com desenvolvimento e segurança, necessidade de uma SIPAT mais interativa e aplicação de conhecimentos em uma situação real. Ele não é apenas uma página de jogos: é uma experiência de aprendizagem aplicada, feita para ajudar outras pessoas a refletir sobre prevenção.</p></div><div className="rounded-2xl border border-[#da291c]/40 bg-gradient-to-br from-red-950/40 to-[#171b24] p-8"><ShieldCheck className="h-8 w-8 text-red-300" aria-hidden="true" /><h3 className="mt-4 font-industrial text-3xl uppercase text-white">Uma construção coletiva</h3><p className="mt-3 text-sm leading-relaxed text-slate-300">Colaboração, criatividade, comunicação e aprendizado transformaram uma ideia em uma plataforma que pode continuar relevante mesmo depois do encerramento da competição.</p></div></div></div></section>

    <section className="border-b border-white/10 bg-[#0f1218] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><InstitutionalGallery compact /></div></section>

    <section className="border-b border-white/10 bg-[#10131a] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="v2-kicker flex items-center gap-2"><Users className="h-3.5 w-3.5" aria-hidden="true" /> Principais criadores</div><p className="mt-3 max-w-3xl text-sm leading-relaxed text-slate-300">A idealização, organização e construção do projeto foram conduzidas por alunos do Formare, com colaboração da turma e apoio das pessoas envolvidas na formação.</p><div className="mt-7 grid gap-4 md:grid-cols-3">{creators.map((creator, index) => <article key={creator.name} className="relative overflow-hidden rounded-xl border border-white/10 bg-[#171b24] p-6 transition hover:-translate-y-1 hover:border-red-500/50"><span className="absolute right-4 top-4 font-mono text-xs text-red-400/70">0{index + 1}</span><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-red-950/50 text-[#da291c]"><Users className="h-5 w-5" aria-hidden="true" /></div><h3 className="mt-8 font-industrial text-2xl uppercase text-white">{creator.name}</h3><div className="mt-3 flex flex-wrap gap-x-3 gap-y-2 text-xs"><a href={`mailto:${creator.email}`} aria-label={`Enviar e-mail para ${creator.name}`} className="inline-flex min-w-0 items-center gap-1.5 text-slate-300 transition hover:text-white focus:outline-none focus:ring-2 focus:ring-red-400"><Mail className="h-3.5 w-3.5 shrink-0 text-red-400" aria-hidden="true" /><span className="break-all">{creator.email}</span></a>{creator.linkedin && <a href={creator.linkedin} target="_blank" rel="noreferrer" aria-label={`Abrir LinkedIn de ${creator.name}`} className="inline-flex min-h-11 items-center gap-1.5 text-slate-300 transition hover:text-white focus:outline-none focus:ring-2 focus:ring-blue-400"><Linkedin className="h-3.5 w-3.5 shrink-0 text-[#6fa8dc]" aria-hidden="true" /> LinkedIn <ExternalLink className="h-3 w-3" aria-hidden="true" /></a>}</div><p className="mt-3 text-xs uppercase tracking-widest text-slate-500">Aluno do Formare</p><p className="mt-4 text-xs leading-relaxed text-slate-400">{creator.role}</p></article>)}</div></div></section>

    <section className="px-4 py-10 text-center sm:px-6 lg:px-8"><p className="mx-auto max-w-3xl text-xs leading-relaxed text-slate-500">As informações sobre o Formare e o projeto devem ser revisadas pelos responsáveis oficiais antes de uso institucional formal. Não foram incluídos depoimentos fictícios.</p></section>
  </main></div>;
}
