import React from "react";
import { ArrowRight, BookOpen, Boxes, Gauge, HardHat, Info, MapPin, Rotate3D, ShieldCheck, Wrench } from "lucide-react";
import { Link } from "wouter";
import { Navbar } from "@/components/Navbar";
import { AxleAssemblyViewer } from "@/components/AxleAssemblyViewer";

const highlights = [
  { icon: Boxes, title: "Redução simples", text: "Arquitetura de eixo traseiro simples para aplicações de transporte e entrega." },
  { icon: Gauge, title: "18,1 t de GCW", text: "Peso combinado bruto informado pela Cummins: 18,1 toneladas / 40.000 lb." },
  { icon: ShieldCheck, title: "6,8 t de GAWR", text: "Classificação de peso bruto por eixo: 6,8 toneladas / 15.000 lb." },
  { icon: Wrench, title: "Configuração flexível", text: "Relações disponíveis de 3.31 a 7.17 e bloqueio diferencial opcional." },
  { icon: HardHat, title: "Uso urbano e em linha", text: "Projetado para caminhões e ônibus em transporte e entrega urbana." },
  { icon: MapPin, title: "Carcaça em Osasco", text: "A carcaça do MS-120 passou a ser fabricada na unidade de Osasco." },
];

const specs = [
  ["Produto", "MS-120"], ["Tipo", "Eixo traseiro simples"], ["Redução", "Simples"], ["Aplicações", "Transporte em linha e entrega urbana"], ["Veículos", "Caminhões e ônibus"], ["GCW", "18,1 t / 40.000 lb"], ["GAWR", "6,8 t / 15.000 lb"], ["Carga vertical sobre o eixo", "6.804 kg"], ["Carga combinada", "18.144 kg"], ["Peso informado", "175 kg, sem lubrificante, freios, cubos e tambores"], ["Seção da carcaça", "108 x 97 mm"], ["Espessura da parede", "11 mm"], ["Diâmetro do semieixo", "41,1 mm"], ["Estriado do semieixo", "44,5 mm"], ["Rolamentos do cubo", "80 mm entre rolamentos"], ["Bitola", "1.688 mm, conforme necessidade"], ["Bloqueio do diferencial", "Opcional"], ["Extremidades", "Tipo F"], ["Relações disponíveis", "3.31, 3.58, 3.73, 3.91, 4.10, 4.30, 4.56, 4.88, 5.13, 5.29, 5.57, 5.86, 6.14, 6.83 e 7.17"],
];

export default function Projeto3D() {
  return <div className="min-h-screen bg-[#0d0f13] text-slate-100"><Navbar /><main>
    <section className="border-b border-white/10 bg-[radial-gradient(circle_at_80%_10%,rgba(218,41,28,.2),transparent_35%),linear-gradient(135deg,#171b24,#0d0f13)] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="v2-kicker flex items-center gap-2"><Rotate3D className="h-3.5 w-3.5" /> CDBS OSASCO / EXPERIÊNCIA TÉCNICA</div><h1 className="mt-4 font-industrial text-5xl uppercase leading-[.92] text-white sm:text-8xl">Projeto<br /><span className="text-[#da291c]">3D.</span></h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-slate-300">Explore um modelo digital 3D do eixo traseiro simples Cummins MS-120, construído com objetos mecânicos independentes e informações técnicas verificáveis. Gire, aproxime, consulte mais de 50 componentes catalogados e abra uma vista explodida do conjunto.</p><div className="mt-6 flex flex-wrap gap-2"><span className="rounded-md border border-red-400/30 bg-red-950/30 px-3 py-2 text-xs font-bold uppercase tracking-wide text-red-200">MS-120</span><span className="rounded-md border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold uppercase tracking-wide text-slate-300">Eixo traseiro simples</span><span className="rounded-md border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold uppercase tracking-wide text-slate-300">Treinamento técnico</span></div></div></section>

    <section className="border-b border-white/10 bg-[#12151d] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-3"><Rotate3D className="h-6 w-6 text-[#da291c]" /><div><div className="v2-kicker">Modelo mecânico reconstruído</div><h2 className="font-industrial text-3xl uppercase text-white">Explore o MS-120</h2></div></div><p className="mt-4 max-w-3xl text-sm leading-relaxed text-slate-400">O eixo é exibido primeiro <b>totalmente montado</b>, como estaria fisicamente instalado em um caminhão ou ônibus: a carcaça envolve o diferencial, os semieixos estão instalados e o conjunto do pinhão está conectado à carcaça. O diferencial é modelado como um conjunto mecânico real — caixa, coroa, cruzeta, satélites, planetárias e rolamentos — e não como uma esfera genérica. Só ao clicar em "Exploded view" cada peça se afasta pelo seu eixo real de montagem, com animação progressiva e reversível.</p><div className="mt-7"><AxleAssemblyViewer /></div></div></section>

    <section className="border-b border-white/10 bg-[#0f1218] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="v2-kicker">Pontos principais do MS-120</div><h2 className="mt-2 font-industrial text-3xl uppercase text-white">Arquitetura e aplicação</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{highlights.map((item) => <article key={item.title} className="rounded-xl border border-white/10 bg-[#141822] p-5 transition hover:-translate-y-1 hover:border-red-500/50"><item.icon className="h-7 w-7 text-[#da291c]" /><h3 className="mt-7 font-industrial text-xl uppercase text-white">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{item.text}</p></article>)}</div></div></section>

    <section className="border-b border-white/10 bg-[#12151d] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-3"><BookOpen className="h-6 w-6 text-amber-400" /><div><div className="v2-kicker">Consulta técnica</div><h2 className="font-industrial text-3xl uppercase text-white">Ficha do produto</h2></div></div><div className="mt-7 overflow-hidden rounded-xl border border-white/10"><div className="overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left text-sm"><thead className="bg-[#1a202b] text-xs uppercase tracking-wider text-slate-300"><tr><th className="px-5 py-4">Campo</th><th className="px-5 py-4">Informação</th></tr></thead><tbody>{specs.map(([field, value], index) => <tr key={field} className={index % 2 ? "bg-[#141822]" : "bg-[#10141b]"}><th scope="row" className="w-1/3 px-5 py-3 font-semibold text-slate-300">{field}</th><td className="px-5 py-3 leading-relaxed text-slate-400">{value}</td></tr>)}</tbody></table></div></div></div></section>

    <section className="border-b border-white/10 bg-gradient-to-r from-red-950/30 via-[#151922] to-black px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><div className="rounded-xl border border-red-400/25 bg-red-950/20 p-6"><div className="flex items-center gap-2 text-red-200"><MapPin className="h-5 w-5" /><h2 className="font-industrial text-2xl uppercase">Contexto brasileiro</h2></div><p className="mt-4 text-sm leading-relaxed text-slate-300">A carcaça do eixo MS-120 passou a ser fabricada pela unidade da Cummins em Osasco, São Paulo. Essa informação se refere à nacionalização da carcaça e à produção local do componente; não é uma especificação dimensional adicional do eixo.</p><p className="mt-4 text-xs leading-relaxed text-slate-400">A carcaça também foi associada a uma versão ECO — Electric Compatible — desenvolvida pela engenharia brasileira para veículos elétricos.</p></div><div className="rounded-xl border border-amber-400/20 bg-amber-950/10 p-6"><div className="flex items-center gap-2 text-amber-200"><Info className="h-5 w-5" /><h2 className="font-industrial text-2xl uppercase">Origem do modelo</h2></div><p className="mt-4 text-sm leading-relaxed text-slate-300">A geometria é reconstruída proceduralmente a partir das especificações públicas do MS-120 e de referências visuais de eixos Cummins/Meritor 17XS, sem usar fotografias como textura. Para fabricação, continuam sendo necessários desenhos, tolerâncias e especificações oficiais do fabricante.</p></div></div></section>

    <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="v2-kicker">Fontes técnicas</div><h2 className="mt-2 font-industrial text-3xl uppercase text-white">Consulte as referências</h2><div className="mt-6 grid gap-3 md:grid-cols-3"><a href="https://www.cummins.com/pt-br/components/products/drivetrain-systems/axles/single-rear-drive/ms-120" target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 bg-[#141822] p-4 text-sm text-slate-300 hover:border-red-400/60 hover:text-white focus:outline-none focus:ring-2 focus:ring-red-400">Cummins — página oficial do MS-120 <ArrowRight className="ml-1 inline h-4 w-4" /></a><a href="https://www.meritorbrasil.com.br/eixos-ms.php" target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 bg-[#141822] p-4 text-sm text-slate-300 hover:border-red-400/60 hover:text-white focus:outline-none focus:ring-2 focus:ring-red-400">Ficha brasileira de eixos <ArrowRight className="ml-1 inline h-4 w-4" /></a><a href="https://www.autodata.com.br/noticias/2024/04/03/cummins-meritor-nacionaliza-a-carcaca-do-eixo-ms-120/70197/" target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 bg-[#141822] p-4 text-sm text-slate-300 hover:border-red-400/60 hover:text-white focus:outline-none focus:ring-2 focus:ring-red-400">AutoData — nacionalização da carcaça <ArrowRight className="ml-1 inline h-4 w-4" /></a></div><div className="mt-8"><Link href="/jogos" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-red-300 hover:text-white">Voltar aos desafios <ArrowRight className="h-4 w-4" /></Link></div></div></section>
  </main></div>;
}
