/**
 * Catálogo Oficial e Padronizado de Perguntas da SIPAT Cummins Osasco
 * Estruturado com validação por nível de dificuldade real, tempo, pontuação e objetivo educativo.
 *
 * Cada pergunta possui:
 * - gameType: quiz_seguranca | quiz_ergonomia
 * - difficulty: facil | medio | dificil
 * - theme: área temática
 * - question: enunciado contextualizado
 * - optionA, optionB, optionC, optionD: alternativas plausíveis e equilibradas
 * - correctOption: A | B | C | D
 * - explanation: justificativa técnica educativa detalhada
 * - educationalObjective: competência comportamental e técnica avaliada
 */

export interface DetailedQuizQuestion {
  gameType: "quiz_seguranca" | "quiz_ergonomia";
  difficulty: "facil" | "medio" | "dificil";
  theme: string;
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: "A" | "B" | "C" | "D";
  explanation: string;
  educationalObjective: string;
}

export const OFFICIAL_QUIZ_QUESTIONS: DetailedQuizQuestion[] = [
  // =========================================================================
  // QUIZ DE SEGURANÇA - NÍVEL FÁCIL (Conhecimentos fundamentais, situações diretas)
  // =========================================================================
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Red Flag & Cultura Preventiva",
    question: "Ao identificar uma condição insegura imediata no posto (óleo no chão ou proteção solta), qual é a conduta correta do Red Flag?",
    optionA: "Ignorar e continuar a produção para não comprometer a meta do turno",
    optionB: "Parar a atividade com segurança, sinalizar a área e comunicar imediatamente a liderança",
    optionC: "Anotar em um caderno pessoal e esperar a próxima reunião semanal",
    optionD: "Tentar resolver sozinho sem ferramentas adequadas nem treinamento",
    correctOption: "B",
    explanation: "O Red Flag na Cummins é o compromisso inegociável de interromper o trabalho diante do risco, sinalizar para proteger os colegas e comunicar na hora.",
    educationalObjective: "Consolidar o direito e o dever de recusa segura e comunicação imediata de desvios.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "EPI & Circulação Operacional",
    question: "Nas áreas operacionais da fábrica Cummins Osasco, qual combinação de proteção básica é obrigatória para qualquer circulação?",
    optionA: "Óculos de segurança com proteção lateral e calçado de segurança com biqueira",
    optionB: "Apenas protetor auricular, dispensando calçado se estiver na faixa amarela",
    optionC: "Roupas esportivas confortáveis e fones de ouvido comuns para comunicação",
    optionD: "Óculos escuros comuns de sol e tênis de caminhada",
    correctOption: "A",
    explanation: "A proteção ocular lateral e os calçados com biqueira protegem contra projeção de partículas e queda de peças pesadas.",
    educationalObjective: "Garantir o uso correto e contínuo dos EPIs básicos obrigatórios.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Organização & 5S",
    question: "Como a prática do 5S na bancada de trabalho contribui diretamente para evitar acidentes?",
    optionA: "Serve apenas para estética quando a fábrica recebe visitantes externos",
    optionB: "Elimina itens desnecessários, mantém ferramentas acessíveis e evita tropeços e cortes",
    optionC: "Aumenta o tempo necessário para encontrar parafusos e componentes",
    optionD: "Substitui a necessidade de usar óculos e luvas nas operações",
    correctOption: "B",
    explanation: "Postos organizados e limpos eliminam condições inseguras na origem, evitam quedas de ferramentas e tornam vazamentos visíveis.",
    educationalObjective: "Vincular a organização física do posto à redução direta de riscos de acidentes.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Procedimentos de Emergência",
    question: "Ao soar o alarme sonoro de evacuação geral de emergência, qual deve ser a sua atitude imediata?",
    optionA: "Correr desesperadamente atropelando os colegas até a portaria principal",
    optionB: "Desligar equipamentos com segurança rápida, seguir as rotas de fuga sinalizadas e ir ao Ponto de Encontro",
    optionC: "Voltar ao vestiário para resgatar mochilas, carteiras e pertences pessoais",
    optionD: "Subir em mezaninos ou empilhadeiras para filmar a ocorrência com o celular",
    correctOption: "B",
    explanation: "A evacuação segura exige calma, uso das saídas de emergência desobstruídas e apresentação no Ponto de Encontro para contagem de vidas.",
    educationalObjective: "Treinar a resposta ordenada e padronizada em situações de alarme industrial.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Comunicação de Quase-Acidentes",
    question: "Uma peça pesada quase escorregou e caiu sobre o pé de um colega, mas ninguém se feriu. O que deve ser feito?",
    optionA: "Dar risada com o colega e não contar para ninguém, pois nada aconteceu",
    optionB: "Registrar o quase-acidente para que a causa seja analisada e o risco eliminado antes que vire lesão",
    optionC: "Apenas guardar a peça escondida para não receber bronca da supervisão",
    optionD: "Culpar o colega e exigir que ele trabalhe em outro setor",
    correctOption: "B",
    explanation: "Quase-acidentes são avisos preciosos. Registrá-los permite atuar na causa-raiz e salvar vidas na rotina.",
    educationalObjective: "Estimular a cultura de relato proativo e preventivo sem viés punitivo.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Ferramentas Manuais",
    question: "Ao constatar que um martelo está com o cabo trincado ou uma chave sextavada está gasta e espanando parafusos, qual ação adotar?",
    optionA: "Passar fita isolante no cabo e continuar usando até o fim da semana",
    optionB: "Retirar a ferramenta imediatamente de uso, etiquetar e substituir por uma ferramenta íntegra",
    optionC: "Emprestar a ferramenta danificada para outro colega que não tenha ferramentas",
    optionD: "Bater com mais força para compensar o desgaste da chave",
    correctOption: "B",
    explanation: "Ferramentas manuais improvisadas ou danificadas são grandes causas de lesões nas mãos e nos olhos.",
    educationalObjective: "Inspecionar ferramentas pré-uso e recusar o uso de equipamentos danificados.",
  },

  // =========================================================================
  // QUIZ DE SEGURANÇA - NÍVEL MÉDIO (Cenários combinados, causas-raiz, comparação)
  // =========================================================================
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "LOTO & Energia Zero",
    question: "Antes de desobstruir um transportador motorizado travado na linha de montagem, qual é a sequência correta de segurança?",
    optionA: "Apenas pressionar a botoeira de emergência e colocar a mão com agilidade",
    optionB: "Pedir para alguém segurar o botão de liga enquanto você puxa a peça",
    optionC: "Desenergizar a fonte primária, aplicar cadeado e etiqueta pessoal (LOTO), e realizar o teste de energia zero",
    optionD: "Reduzir a velocidade do motor pelo potenciômetro da esteira",
    correctOption: "C",
    explanation: "O bloqueio de energias perigosas (LOTO) só é seguro após a aplicação de cadeado exclusivo e o teste físico de ausência de energia.",
    educationalObjective: "Validar o protocolo formal de Lockout & Tagout em intervenções de manutenção e produção.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Interação Homem-Máquina & Circulação",
    question: "Ao caminhar por um cruzamento com grande tráfego de empilhadeiras e rebocadores na fábrica, qual regra de ouro deve prevalecer?",
    optionA: "Presumir que o operador da empilhadeira sempre enxerga você em qualquer ângulo",
    optionB: "Manter-se na faixa de pedestres, fazer contato visual com o operador e esperar a máquina parar totalmente antes de cruzar",
    optionC: "Atravessar correndo na frente da máquina para liberar a passagem rapidamente",
    optionD: "Olhar para a tela do smartphone desde que esteja dentro da pintura amarela",
    correctOption: "B",
    explanation: "Empilhadeiras têm pontos cegos severos e grande inércia de frenagem. O contato visual e a parada confirmada evitam atropelamentos.",
    educationalObjective: "Prevenir colisões e atropelamentos industriais por meio de contato visual e respeito às rotas.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Içamento de Cargas & Linha de Fogo",
    question: "Durante o transporte de um bloco de motor por ponte rolante, onde os integrantes da equipe NUNCA devem permanecer?",
    optionA: "Atrás da faixa de isolamento do operador da ponte",
    optionB: "Sob a carga suspensa ou no trajeto de queda/balanço (linha de fogo)",
    optionC: "Na cabine de comando acompanhando os limites de carga",
    optionD: "No posto de controle segurando a botoeira remota de emergência",
    correctOption: "B",
    explanation: "A 'linha de fogo' sob ou ao redor de cargas suspensas nunca pode ser invadida, pois falhas em cabos ou olhais provocam acidentes fatais.",
    educationalObjective: "Desenvolver a percepção do risco de estar na linha de fogo em operações de rigging e içamento.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Rotas de Emergência & Bloqueios",
    question: "Uma equipe logística temporariamente estacionou um palete de peças em frente à porta de emergência. Como proceder?",
    optionA: "Aguardar a conclusão do turno para solicitar a retirada pelo operador de empilhadeira",
    optionB: "Considerar aceitável se metade da porta continuar acessível aos colaboradores",
    optionC: "Interromper a ação de bloqueio imediatamente, remover o palete para área correta e reforçar a proibição de obstrução",
    optionD: "Colocar um cone em cima do palete para sinalizar o obstáculo",
    correctOption: "C",
    explanation: "Saídas de emergência e equipamentos de combate a incêndio nunca podem ser bloqueados, nem por um minuto sequer.",
    educationalObjective: "Priorizar a desobstrução contínua e intransigente de rotas de fuga e extintores.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Sistemas Pressurizados & Pneumática",
    question: "Ao identificar um vazamento sibilante em uma mangueira de ar comprimido a 7 bar na linha de montagem, qual é a atitude técnica correta?",
    optionA: "Segurar o furo com a mão ou envolver com fita adesiva comum para estancar o ruído",
    optionB: "Fechar a válvula de corte correspondente, despressurizar o trecho e acionar a manutenção para troca por mangueira certificada",
    optionC: "Ignorar o vazamento, já que o ar comprimido é inofensivo à pele humana",
    optionD: "Aumentar a pressão do compressor para compensar a perda de vazão",
    correctOption: "B",
    explanation: "O ar comprimido em alta pressão pode penetrar na pele e corrente sanguínea provocando embolia grave; jamais tente conter vazamentos com o corpo.",
    educationalObjective: "Compreender os riscos de energia pneumática pressurizada e o procedimento de isolamento.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Produtos Químicos & Descarte",
    question: "Ao utilizar panos e estopas impregnados com solventes ou óleos combustíveis na limpeza de eixos, qual é o descarte correto?",
    optionA: "Jogar na lixeira comum de papéis de escritório para esvaziamento diário",
    optionB: "Depositar em recipiente metálico estanque com tampa de fechamento automático, identificado para resíduos inflamáveis/contaminados",
    optionC: "Deixar secando sobre a bancada próxima a fontes de calor e solda",
    optionD: "Lavar na pia comum de banheiros da unidade",
    correctOption: "B",
    explanation: "Panos com óleos e solventes podem sofrer combustão espontânea e exigem recipientes corta-chamas específicos para resíduos perigosos.",
    educationalObjective: "Cumprir as normas de prevenção contra princípios de incêndio e descarte de produtos químicos perigosos.",
  },

  // =========================================================================
  // QUIZ DE SEGURANÇA - NÍVEL DIFÍCIL (Tomada de decisão crítica, priorização de riscos)
  // =========================================================================
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Proteções Mecânicas & NR-12",
    question: "Durante a produção seriada, o intertravamento de segurança de uma porta de célula robotizada começa a falhar intermitentemente. Qual decisão deve ser tomada?",
    optionA: "Instalar um imã provisório para burlar o sensor e manter a meta de produção até o fim de semana",
    optionB: "Desligar e bloquear a célula imediatamente (LOTO), registrar Red Flag e só retomar após reparo e validação de segurança pela engenharia",
    optionC: "Pedir para o operador trabalhar com um braço esticado sem encostar na porta",
    optionD: "Reduzir a velocidade do robô em 20% mantendo a porta aberta",
    correctOption: "B",
    explanation: "Burlar ou operar com sistemas de segurança NR-12 danificados é infração gravíssima de segurança; a parada com LOTO é mandatória.",
    educationalObjective: "Garantir tolerância zero contra a burla de dispositivos de intertravamento e proteção mecânica.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Trabalho a Quente & Atmosferas Perigosas",
    question: "Uma manutenção emergencial exige solda em estrutura metálica a 8 metros de altura próxima a tubulações industriais. Quais requisitos prévios são mandatórios?",
    optionA: "Apenas autorização verbal do operador mais próximo e um balde com água no chão",
    optionB: "Emissão de Permissão de Trabalho a Quente e Trabalho em Altura (PT/PET), medição de gases, isolamento com mantas antichama, linha de vida e vigia de incêndio dedicado",
    optionC: "Realizar a solda o mais rápido possível para evitar que o calor se propague pelo ar",
    optionD: "Ligar ventiladores comuns de mesa soprando sobre a tubulação para dispersar faíscas",
    correctOption: "B",
    explanation: "Trabalhos a quente em altura combinam múltiplos riscos críticos que exigem autorização formal, retenção de fagulhas e monitoramento contínuo por vigia.",
    educationalObjective: "Aplicar o rigor procedimental em tarefas especiais de alto potencial de gravidade.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Emergência Química Complexa",
    question: "Ao romper-se uma tubulação industrial de fluido de corte aquecido na fábrica, atingindo dois colaboradores, qual é a prioridade número 1 da equipe de resposta?",
    optionA: "Pegar o telefone e postar um aviso no grupo de mensagens da empresa",
    optionB: "Conduzir os atingidos imediatamente ao chuveiro de emergência/lava-olhos por 15 minutos, isolar a fonte com LOTO e acionar brigada médica com a FISPQ em mãos",
    optionC: "Tentar limpar o chão primeiro com estopas para não manchar o piso epóxi",
    optionD: "Aplicar pomadas caseiras e mandar os colaboradores continuarem operando a máquina",
    correctOption: "B",
    explanation: "A lavagem contínua abundante é vital para evitar queimaduras químicas profundas, simultaneamente à contenção da fonte e suporte médico com identificação do produto.",
    educationalObjective: "Priorizar a vida e a descontaminação imediata em acidentes químicos graves.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Intervenção Elétrica & Arco Elétrico",
    question: "Ao abrir um painel de distribuição trifásico para diagnóstico elétrico, quais medidas são legal e tecnicamente exigidas antes de qualquer toque?",
    optionA: "Utilizar calçado de borracha comum e encostar a ponta da chave de fenda para verificar se faísca",
    optionB: "Profissional qualificado/autorizado NR-10, uso de vestimenta antichama (ATPV compatível), luvas de borracha isolante com sobreluva e teste de ausência de tensão com instrumento aferido",
    optionC: "Apenas pedir para os operadores ao lado darem um passo para trás",
    optionD: "Desligar o disjuntor geral da fábrica inteira sem autorização da subestação",
    correctOption: "B",
    explanation: "O risco de choque elétrico e arco voltaico requer qualificação formal NR-10, EPIs com classificação térmica adequada e aferição comprovada de energia zero.",
    educationalObjective: "Reconhecer os perigos invisíveis de arcos elétricos e respeitar o controle de energia elétrica.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Priorização de Riscos Múltiplos",
    question: "Em uma mesma área, você observa: 1) poça de óleo na faixa de pedestres; 2) trabalhador sem óculos manuseando esmeril; 3) empilhadeira manobrando de ré com aviso sonoro inoperante. Qual deve ser a prioridade de contenção imediata?",
    optionA: "Avisar o setor financeiro sobre o custo do óleo derramado",
    optionB: "Interromper imediatamente a operação do esmeril e a manobra da empilhadeira (riscos iminentes a pessoas), sinalizando a poça em seguida para limpeza",
    optionC: "Limpar o óleo primeiro, pois a sujeira visual é mais fácil de notar",
    optionD: "Esperar acontecer um incidente para saber qual era o perigo mais crítico",
    correctOption: "B",
    explanation: "Na hierarquia de priorização de riscos, condições com potencial iminente de cegueira ou esmagamento/morte sobrepõem-se à limpeza do piso, que deve ser isolado.",
    educationalObjective: "Capacitar a tomada de decisão rápida e lógica frente a múltiplos riscos simultâneos.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Investigação & Causa-Raiz",
    question: "Após a ocorrência de um quase-acidente na linha, qual abordagem na investigação garante que o evento nunca mais se repita?",
    optionA: "Focar em apontar um culpado para adverti-lo formalmente na frente da equipe",
    optionB: "Aplicar metodologia de causa-raiz (como 5 Porquês ou Diagrama de Ishikawa), corrigindo falhas de processo, engenharia e padrões de trabalho",
    optionC: "Arquivar o caso sem mudanças para não gerar retrabalho nos relatórios",
    optionD: "Apenas pintar mais uma faixa amarela no chão sem analisar por que a falha aconteceu",
    correctOption: "B",
    explanation: "A verdadeira cultura de segurança investiga as causas sistêmicas e os controles de engenharia, e não a culpa individual, eliminando o risco definitivamente.",
    educationalObjective: "Promover a mentalidade de melhoria contínua através da análise de causa-raiz em SST.",
  },

  {
  gameType: "quiz_seguranca",
  difficulty: "facil",
  theme: "Meio Ambiente • Segregação de Resíduos",
  question: "Ao descartar uma embalagem contaminada com óleo na área de manutenção, qual decisão atende ao padrão ambiental?",
  optionA: "Misturar com papel limpo para reduzir o número de coletores",
  optionB: "Segregar no recipiente identificado para resíduo contaminado e manter a tampa fechada",
  optionC: "Deixar ao lado da máquina até que o coletor faça a ronda",
  optionD: "Lavar a embalagem no ralo para retirar o óleo antes do descarte",
  correctOption: "B",
  explanation: "A segregação na origem evita contaminação cruzada, reduz risco de incêndio e garante destinação ambiental adequada.",
  educationalObjective: "Relacionar segurança, meio ambiente e descarte correto de resíduos industriais."
},
  {
  gameType: "quiz_seguranca",
  difficulty: "medio",
  theme: "Saúde • Fadiga e Atenção",
  question: "Ao perceber que a fadiga está reduzindo sua atenção durante uma tarefa crítica, qual atitude é mais segura?",
  optionA: "Acelerar para terminar antes que a atenção diminua mais",
  optionB: "Comunicar a condição, fazer a pausa prevista e retomar somente em condições seguras",
  optionC: "Pedir que um colega observe enquanto você continua sem interromper o processo",
  optionD: "Consumir qualquer estimulante por conta própria e manter a operação",
  correctOption: "B",
  explanation: "Fadiga altera percepção, julgamento e tempo de reação. Comunicar e usar os controles previstos protege a pessoa e a equipe.",
  educationalObjective: "Reconhecer fatores humanos como parte do controle de riscos industriais."
},

  // =========================================================================
  // QUIZ LEAN MANUFACTURING - 20 perguntas (5S, Kaizen, fluxo, qualidade e melhoria)
  // O identificador técnico quiz_ergonomia é mantido para compatibilidade de banco.
  // =========================================================================
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • 5S",
  question: "No 5S, qual é o objetivo principal do senso de utilização (Seiri)?",
  optionA: "Separar o necessário do desnecessário e retirar excessos do posto",
  optionB: "Aumentar o estoque de segurança em todas as bancadas",
  optionC: "Definir uma cor diferente para cada operador",
  optionD: "Substituir a inspeção de qualidade por limpeza visual",
  correctOption: "A",
  explanation: "O Seiri remove o que não agrega valor ao posto, liberando espaço e reduzindo obstáculos, procura e riscos.",
  educationalObjective: "Identificar desperdícios físicos e aplicar o primeiro senso do 5S."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • 5S",
  question: "Qual prática representa melhor o senso de ordenação (Seiton)?",
  optionA: "Guardar todos os itens em um armário fechado sem identificação",
  optionB: "Definir local, identificação e quantidade visual para cada item usado no processo",
  optionC: "Manter ferramentas espalhadas para que cada pessoa escolha onde deixar",
  optionD: "Concentrar materiais de todos os setores em uma única área",
  correctOption: "B",
  explanation: "O Seiton torna o fluxo visual: cada coisa tem lugar definido, identificação clara e acesso rápido.",
  educationalObjective: "Aplicar organização visual para reduzir procura e movimentação desnecessária."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • Fluxo",
  question: "Em um fluxo contínuo, qual sinal indica que há provável excesso de processo entre duas etapas?",
  optionA: "Peças aguardando em fila por mais tempo do que o necessário",
  optionB: "Uma instrução de trabalho disponível no ponto de uso",
  optionC: "Uma inspeção feita na origem do processo",
  optionD: "Um operador treinado para mais de uma atividade",
  correctOption: "A",
  explanation: "Filas e estoques intermediários escondem problemas e aumentam o lead time sem entregar valor ao cliente.",
  educationalObjective: "Reconhecer espera e estoque intermediário como sinais de fluxo interrompido."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • Trabalho Padronizado",
  question: "Por que o trabalho padronizado é importante em uma operação repetitiva?",
  optionA: "Para impedir qualquer melhoria feita pelo operador",
  optionB: "Para registrar a melhor sequência conhecida e criar uma base segura para melhorar",
  optionC: "Para permitir que cada pessoa escolha um método diferente a cada ciclo",
  optionD: "Para eliminar a necessidade de treinar novos colaboradores",
  correctOption: "B",
  explanation: "O padrão estabiliza o processo, facilita treinamento e permite comparar resultados antes e depois de uma melhoria.",
  educationalObjective: "Relacionar padrão, estabilidade e melhoria contínua."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • Qualidade na Fonte",
  question: "O que significa qualidade na fonte em uma linha Lean?",
  optionA: "Deixar a inspeção somente para o final do turno",
  optionB: "Identificar e conter o defeito no ponto em que ele é criado",
  optionC: "Enviar o lote adiante para que outro setor decida o que fazer",
  optionD: "Aumentar a velocidade para produzir peças suficientes para compensar defeitos",
  correctOption: "B",
  explanation: "Detectar e conter o problema na origem evita propagação de defeitos e reduz retrabalho.",
  educationalObjective: "Compreender prevenção de defeitos e responsabilidade compartilhada pela qualidade."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • Kaizen",
  question: "Qual característica define uma ação Kaizen bem aplicada?",
  optionA: "Uma mudança pequena, observada no processo e sustentada por um padrão atualizado",
  optionB: "Uma grande mudança feita sem envolver quem executa o trabalho",
  optionC: "Uma ideia que melhora apenas a aparência do setor",
  optionD: "Uma alteração que não precisa ser medida depois de implantada",
  correctOption: "A",
  explanation: "Kaizen combina participação, experimentação, medição e sustentação do novo modo de trabalho.",
  educationalObjective: "Aplicar o ciclo de melhoria contínua em ações práticas de baixo risco."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "facil",
  theme: "Lean • Desperdícios",
  question: "Qual situação representa principalmente desperdício de movimentação?",
  optionA: "O operador caminhar repetidamente até um armário distante para buscar a mesma ferramenta",
  optionB: "Uma peça ser montada conforme a sequência definida",
  optionC: "Uma anomalia ser sinalizada no ponto de ocorrência",
  optionD: "Um material ser entregue na quantidade planejada",
  correctOption: "A",
  explanation: "Movimentos adicionais que não transformam o produto consomem tempo e podem aumentar a exposição a riscos.",
  educationalObjective: "Identificar movimentação desnecessária e oportunidade de melhoria de layout."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • Kanban",
  question: "Qual é a função de um sistema Kanban em um fluxo puxado?",
  optionA: "Autorizar produção ou reposição conforme o consumo e o sinal visual definido",
  optionB: "Produzir o máximo possível antes de receber qualquer demanda",
  optionC: "Substituir todos os padrões de qualidade por cartões coloridos",
  optionD: "Aumentar o estoque intermediário para evitar qualquer parada",
  correctOption: "A",
  explanation: "O Kanban sinaliza necessidade de reposição ou produção com base no consumo real, evitando excesso.",
  educationalObjective: "Distinguir fluxo puxado de produção empurrada e compreender o papel do sinal visual."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • Just in Time",
  question: "Qual é o principal cuidado ao aplicar Just in Time em uma operação crítica?",
  optionA: "Eliminar estoques sem estabilizar fornecedores, qualidade e processo",
  optionB: "Sincronizar abastecimento com consumo, mantendo controles para evitar interrupções",
  optionC: "Aumentar lotes para ocupar toda a capacidade disponível",
  optionD: "Armazenar materiais em qualquer local desde que estejam próximos",
  correctOption: "B",
  explanation: "Just in Time depende de estabilidade, qualidade e abastecimento confiável; reduzir estoque sem essas bases aumenta o risco.",
  educationalObjective: "Entender que fluxo puxado exige estabilidade e não significa simplesmente zerar estoques."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • OEE",
  question: "O indicador OEE combina quais dimensões do desempenho de um equipamento?",
  optionA: "Disponibilidade, performance e qualidade",
  optionB: "Custo, estoque e número de operadores",
  optionC: "Segurança, clima e satisfação do cliente",
  optionD: "Peso, volume e velocidade máxima de projeto",
  correctOption: "A",
  explanation: "OEE mostra quanto do tempo planejado resulta em produção boa, combinando disponibilidade, performance e qualidade.",
  educationalObjective: "Interpretar as dimensões básicas de eficiência global do equipamento."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • SMED",
  question: "Uma ação típica de SMED para reduzir setup é:",
  optionA: "Transformar atividades internas em externas e preparar ferramentas antes da parada",
  optionB: "Esperar o equipamento parar para começar a procurar todos os materiais",
  optionC: "Aumentar o lote para nunca mais realizar troca",
  optionD: "Retirar verificações de segurança para ganhar alguns minutos",
  correctOption: "A",
  explanation: "SMED reduz tempo de troca separando o que pode ser preparado com a máquina em operação do que exige parada.",
  educationalObjective: "Reconhecer a separação entre atividades internas e externas de setup."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • Causa-Raiz",
  question: "Ao surgir um defeito repetitivo, qual uso dos 5 Porquês é mais adequado?",
  optionA: "Parar no primeiro sintoma e responsabilizar a última pessoa que tocou na peça",
  optionB: "Investigar causas progressivamente até encontrar uma condição de processo controlável",
  optionC: "Escolher a causa que exigir menor investimento, sem confirmar no local",
  optionD: "Substituir a análise por uma nova inspeção no fim da linha",
  correctOption: "B",
  explanation: "Os 5 Porquês devem levar a uma causa-raiz verificável e a uma ação que evite a recorrência.",
  educationalObjective: "Usar investigação estruturada sem confundir sintoma com causa-raiz."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • Heijunka",
  question: "O nivelamento (Heijunka) busca principalmente:",
  optionA: "Distribuir volume e mix de forma mais estável para reduzir oscilações e sobrecarga",
  optionB: "Produzir somente o item mais fácil durante todo o turno",
  optionC: "Concentrar a produção em lotes cada vez maiores",
  optionD: "Eliminar a necessidade de sequenciamento e planejamento",
  correctOption: "A",
  explanation: "O nivelamento reduz picos e vales de demanda, ajudando o processo a operar com fluxo mais previsível.",
  educationalObjective: "Relacionar nivelamento de produção com estabilidade de fluxo e capacidade."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "medio",
  theme: "Lean • Gestão Visual",
  question: "Qual é a melhor característica de um quadro de gestão visual no posto?",
  optionA: "Mostrar indicadores atualizados, padrão esperado, desvio e responsável pela reação",
  optionB: "Exibir apenas metas anuais para evitar preocupação com variações diárias",
  optionC: "Usar muitas cores e números sem definição para parecer mais completo",
  optionD: "Registrar resultados sem discutir os desvios com a equipe",
  correctOption: "A",
  explanation: "Gestão visual transforma o desvio em ação: o time precisa saber o padrão, o estado atual e como reagir.",
  educationalObjective: "Avaliar se um controle visual realmente orienta reação rápida e padronizada."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "dificil",
  theme: "Lean • Fluxo de Valor",
  question: "Ao iniciar um mapa de fluxo de valor, qual sequência oferece melhor diagnóstico?",
  optionA: "Mapear o estado atual, observar fluxo de material e informação, e depois desenhar um estado futuro",
  optionB: "Desenhar o estado futuro sem medir lead time, estoque ou demanda",
  optionC: "Mapear apenas a máquina mais lenta e ignorar fornecedores e cliente",
  optionD: "Começar pela compra de um software sem ir ao gemba",
  correctOption: "A",
  explanation: "O mapa começa com fatos do estado atual e usa esses dados para desenhar um estado futuro coerente.",
  educationalObjective: "Aplicar visão sistêmica ao diagnóstico de fluxo de valor."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "dificil",
  theme: "Lean • Gemba",
  question: "O que caracteriza uma visita ao gemba com qualidade?",
  optionA: "Ir ao local, observar o trabalho real, perguntar com respeito e comparar fatos com o padrão",
  optionB: "Avaliar o processo apenas por relatórios e cobrar respostas na sala de reunião",
  optionC: "Procurar um culpado antes de entender as condições do processo",
  optionD: "Alterar o padrão imediatamente sem testar a causa observada",
  correctOption: "A",
  explanation: "Gemba significa observar o trabalho onde ele acontece, com foco em fatos, respeito e aprendizagem.",
  educationalObjective: "Diferenciar gestão baseada em fatos de julgamento distante do processo."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "dificil",
  theme: "Lean • Poka-Yoke",
  question: "Qual solução é um exemplo de poka-yoke?",
  optionA: "Um dispositivo que impede o encaixe invertido e confirma a presença do componente correto",
  optionB: "Uma inspeção visual feita somente depois que o lote foi concluído",
  optionC: "Um aviso genérico colocado no mural do setor",
  optionD: "Uma meta maior para estimular atenção do operador",
  correctOption: "A",
  explanation: "Poka-yoke evita o erro ou o detecta imediatamente, preferencialmente antes que avance para a próxima etapa.",
  educationalObjective: "Reconhecer dispositivos à prova de erro como controle de processo."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "dificil",
  theme: "Lean • A3 e Melhoria",
  question: "Em um relatório A3, qual relação entre problema, causa e contramedida é a mais consistente?",
  optionA: "A contramedida deve atacar causas confirmadas e possuir indicador, responsável e prazo de acompanhamento",
  optionB: "A contramedida deve ser escolhida antes de observar o problema para ganhar velocidade",
  optionC: "O A3 deve registrar somente o resultado final, sem explicar o raciocínio",
  optionD: "Toda causa exige uma ação de treinamento, independentemente da evidência",
  correctOption: "A",
  explanation: "O A3 organiza raciocínio, fatos, causa-raiz, contramedidas e acompanhamento para sustentar a melhoria.",
  educationalObjective: "Estruturar solução de problemas com evidência, responsabilidade e verificação."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "dificil",
  theme: "Lean • Variabilidade",
  question: "Por que reduzir variabilidade é importante antes de diminuir estoques de proteção?",
  optionA: "Porque processos instáveis consomem o estoque com interrupções e escondem causas de falha",
  optionB: "Porque estoque nunca deve existir, mesmo quando há risco de parada crítica",
  optionC: "Porque variabilidade afeta somente o custo financeiro e não o atendimento",
  optionD: "Porque diminuir estoque elimina automaticamente todos os defeitos",
  correctOption: "A",
  explanation: "Estabilidade de processo, qualidade e abastecimento reduzem a necessidade de buffers e tornam o fluxo previsível.",
  educationalObjective: "Compreender a relação entre estabilidade, variabilidade e estoques de proteção."
},
  {
  gameType: "quiz_ergonomia",
  difficulty: "dificil",
  theme: "Lean • Sustentação",
  question: "Depois de uma melhoria atingir o resultado esperado, qual ação evita que o ganho desapareça?",
  optionA: "Atualizar o padrão, treinar a equipe, acompanhar indicadores e reagir aos desvios",
  optionB: "Encerrar o acompanhamento para permitir que cada turno adapte o método",
  optionC: "Guardar a solução com o líder do projeto e não alterar a instrução de trabalho",
  optionD: "Aumentar a meta imediatamente sem verificar segurança e qualidade",
  correctOption: "A",
  explanation: "Sem padronização, treinamento e acompanhamento, a melhoria tende a regredir quando mudam pessoas ou condições.",
  educationalObjective: "Sustentar ganhos de melhoria contínua com padrão e gestão diária."
},
];
