/**
 * Catálogo Oficial e Padronizado de Perguntas da SIPAT Cummins Osasco
 * Estruturado com validação por nível de dificuldade real, tempo, pontuação e objetivo educativo.
 *
 * Cada pergunta possui:
 * - gameType: quiz_seguranca | quiz_ergonomia
 * - difficulty: facil | medio | dificil
 * - theme: área temática
 * - question: enunciado contextualizado
 * - optionA, optionB, optionC, optionD: alternativas plausíveis e equilibradas
 * - correctOption: A | B | C | D
 * - explanation: justificativa técnica educativa detalhada
 * - educationalObjective: competência comportamental e técnica avaliada
 */

export interface DetailedQuizQuestion {
  gameType: "quiz_seguranca" | "quiz_ergonomia";
  difficulty: "facil" | "medio" | "dificil";
  theme: string;
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: "A" | "B" | "C" | "D";
  explanation: string;
  educationalObjective: string;
}

export const OFFICIAL_QUIZ_QUESTIONS: DetailedQuizQuestion[] = [
  // =========================================================================
  // QUIZ DE SEGURANÇA - NÍVEL FÁCIL (Conhecimentos fundamentais, situações diretas)
  // =========================================================================
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Red Flag & Cultura Preventiva",
    question: "Ao identificar uma condição insegura imediata no posto (óleo no chão ou proteção solta), qual é a conduta correta do Red Flag?",
    optionA: "Ignorar e continuar a produção para não comprometer a meta do turno",
    optionB: "Parar a atividade com segurança, sinalizar a área e comunicar imediatamente a liderança",
    optionC: "Anotar em um caderno pessoal e esperar a próxima reunião semanal",
    optionD: "Tentar resolver sozinho sem ferramentas adequadas nem treinamento",
    correctOption: "B",
    explanation: "O Red Flag na Cummins é o compromisso inegociável de interromper o trabalho diante do risco, sinalizar para proteger os colegas e comunicar na hora.",
    educationalObjective: "Consolidar o direito e o dever de recusa segura e comunicação imediata de desvios.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "EPI & Circulação Operacional",
    question: "Nas áreas operacionais da fábrica Cummins Osasco, qual combinação de proteção básica é obrigatória para qualquer circulação?",
    optionA: "Óculos de segurança com proteção lateral e calçado de segurança com biqueira",
    optionB: "Apenas protetor auricular, dispensando calçado se estiver na faixa amarela",
    optionC: "Roupas esportivas confortáveis e fones de ouvido comuns para comunicação",
    optionD: "Óculos escuros comuns de sol e tênis de caminhada",
    correctOption: "A",
    explanation: "A proteção ocular lateral e os calçados com biqueira protegem contra projeção de partículas e queda de peças pesadas.",
    educationalObjective: "Garantir o uso correto e contínuo dos EPIs básicos obrigatórios.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Organização & 5S",
    question: "Como a prática do 5S na bancada de trabalho contribui diretamente para evitar acidentes?",
    optionA: "Serve apenas para estética quando a fábrica recebe visitantes externos",
    optionB: "Elimina itens desnecessários, mantém ferramentas acessíveis e evita tropeços e cortes",
    optionC: "Aumenta o tempo necessário para encontrar parafusos e componentes",
    optionD: "Substitui a necessidade de usar óculos e luvas nas operações",
    correctOption: "B",
    explanation: "Postos organizados e limpos eliminam condições inseguras na origem, evitam quedas de ferramentas e tornam vazamentos visíveis.",
    educationalObjective: "Vincular a organização física do posto à redução direta de riscos de acidentes.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Procedimentos de Emergência",
    question: "Ao soar o alarme sonoro de evacuação geral de emergência, qual deve ser a sua atitude imediata?",
    optionA: "Correr desesperadamente atropelando os colegas até a portaria principal",
    optionB: "Desligar equipamentos com segurança rápida, seguir as rotas de fuga sinalizadas e ir ao Ponto de Encontro",
    optionC: "Voltar ao vestiário para resgatar mochilas, carteiras e pertences pessoais",
    optionD: "Subir em mezaninos ou empilhadeiras para filmar a ocorrência com o celular",
    correctOption: "B",
    explanation: "A evacuação segura exige calma, uso das saídas de emergência desobstruídas e apresentação no Ponto de Encontro para contagem de vidas.",
    educationalObjective: "Treinar a resposta ordenada e padronizada em situações de alarme industrial.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Comunicação de Quase-Acidentes",
    question: "Uma peça pesada quase escorregou e caiu sobre o pé de um colega, mas ninguém se feriu. O que deve ser feito?",
    optionA: "Dar risada com o colega e não contar para ninguém, pois nada aconteceu",
    optionB: "Registrar o quase-acidente para que a causa seja analisada e o risco eliminado antes que vire lesão",
    optionC: "Apenas guardar a peça escondida para não receber bronca da supervisão",
    optionD: "Culpar o colega e exigir que ele trabalhe em outro setor",
    correctOption: "B",
    explanation: "Quase-acidentes são avisos preciosos. Registrá-los permite atuar na causa-raiz e salvar vidas na rotina.",
    educationalObjective: "Estimular a cultura de relato proativo e preventivo sem viés punitivo.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "facil",
    theme: "Ferramentas Manuais",
    question: "Ao constatar que um martelo está com o cabo trincado ou uma chave sextavada está gasta e espanando parafusos, qual ação adotar?",
    optionA: "Passar fita isolante no cabo e continuar usando até o fim da semana",
    optionB: "Retirar a ferramenta imediatamente de uso, etiquetar e substituir por uma ferramenta íntegra",
    optionC: "Emprestar a ferramenta danificada para outro colega que não tenha ferramentas",
    optionD: "Bater com mais força para compensar o desgaste da chave",
    correctOption: "B",
    explanation: "Ferramentas manuais improvisadas ou danificadas são grandes causas de lesões nas mãos e nos olhos.",
    educationalObjective: "Inspecionar ferramentas pré-uso e recusar o uso de equipamentos danificados.",
  },

  // =========================================================================
  // QUIZ DE SEGURANÇA - NÍVEL MÉDIO (Cenários combinados, causas-raiz, comparação)
  // =========================================================================
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "LOTO & Energia Zero",
    question: "Antes de desobstruir um transportador motorizado travado na linha de montagem, qual é a sequência correta de segurança?",
    optionA: "Apenas pressionar a botoeira de emergência e colocar a mão com agilidade",
    optionB: "Pedir para alguém segurar o botão de liga enquanto você puxa a peça",
    optionC: "Desenergizar a fonte primária, aplicar cadeado e etiqueta pessoal (LOTO), e realizar o teste de energia zero",
    optionD: "Reduzir a velocidade do motor pelo potenciômetro da esteira",
    correctOption: "C",
    explanation: "O bloqueio de energias perigosas (LOTO) só é seguro após a aplicação de cadeado exclusivo e o teste físico de ausência de energia.",
    educationalObjective: "Validar o protocolo formal de Lockout & Tagout em intervenções de manutenção e produção.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Interação Homem-Máquina & Circulação",
    question: "Ao caminhar por um cruzamento com grande tráfego de empilhadeiras e rebocadores na fábrica, qual regra de ouro deve prevalecer?",
    optionA: "Presumir que o operador da empilhadeira sempre enxerga você em qualquer ângulo",
    optionB: "Manter-se na faixa de pedestres, fazer contato visual com o operador e esperar a máquina parar totalmente antes de cruzar",
    optionC: "Atravessar correndo na frente da máquina para liberar a passagem rapidamente",
    optionD: "Olhar para a tela do smartphone desde que esteja dentro da pintura amarela",
    correctOption: "B",
    explanation: "Empilhadeiras têm pontos cegos severos e grande inércia de frenagem. O contato visual e a parada confirmada evitam atropelamentos.",
    educationalObjective: "Prevenir colisões e atropelamentos industriais por meio de contato visual e respeito às rotas.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Içamento de Cargas & Linha de Fogo",
    question: "Durante o transporte de um bloco de motor por ponte rolante, onde os integrantes da equipe NUNCA devem permanecer?",
    optionA: "Atrás da faixa de isolamento do operador da ponte",
    optionB: "Sob a carga suspensa ou no trajeto de queda/balanço (linha de fogo)",
    optionC: "Na cabine de comando acompanhando os limites de carga",
    optionD: "No posto de controle segurando a botoeira remota de emergência",
    correctOption: "B",
    explanation: "A 'linha de fogo' sob ou ao redor de cargas suspensas nunca pode ser invadida, pois falhas em cabos ou olhais provocam acidentes fatais.",
    educationalObjective: "Desenvolver a percepção do risco de estar na linha de fogo em operações de rigging e içamento.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Rotas de Emergência & Bloqueios",
    question: "Uma equipe logística temporariamente estacionou um palete de peças em frente à porta de emergência. Como proceder?",
    optionA: "Aguardar a conclusão do turno para solicitar a retirada pelo operador de empilhadeira",
    optionB: "Considerar aceitável se metade da porta continuar acessível aos colaboradores",
    optionC: "Interromper a ação de bloqueio imediatamente, remover o palete para área correta e reforçar a proibição de obstrução",
    optionD: "Colocar um cone em cima do palete para sinalizar o obstáculo",
    correctOption: "C",
    explanation: "Saídas de emergência e equipamentos de combate a incêndio nunca podem ser bloqueados, nem por um minuto sequer.",
    educationalObjective: "Priorizar a desobstrução contínua e intransigente de rotas de fuga e extintores.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Sistemas Pressurizados & Pneumática",
    question: "Ao identificar um vazamento sibilante em uma mangueira de ar comprimido a 7 bar na linha de montagem, qual é a atitude técnica correta?",
    optionA: "Segurar o furo com a mão ou envolver com fita adesiva comum para estancar o ruído",
    optionB: "Fechar a válvula de corte correspondente, despressurizar o trecho e acionar a manutenção para troca por mangueira certificada",
    optionC: "Ignorar o vazamento, já que o ar comprimido é inofensivo à pele humana",
    optionD: "Aumentar a pressão do compressor para compensar a perda de vazão",
    correctOption: "B",
    explanation: "O ar comprimido em alta pressão pode penetrar na pele e corrente sanguínea provocando embolia grave; jamais tente conter vazamentos com o corpo.",
    educationalObjective: "Compreender os riscos de energia pneumática pressurizada e o procedimento de isolamento.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "medio",
    theme: "Produtos Químicos & Descarte",
    question: "Ao utilizar panos e estopas impregnados com solventes ou óleos combustíveis na limpeza de eixos, qual é o descarte correto?",
    optionA: "Jogar na lixeira comum de papéis de escritório para esvaziamento diário",
    optionB: "Depositar em recipiente metálico estanque com tampa de fechamento automático, identificado para resíduos inflamáveis/contaminados",
    optionC: "Deixar secando sobre a bancada próxima a fontes de calor e solda",
    optionD: "Lavar na pia comum de banheiros da unidade",
    correctOption: "B",
    explanation: "Panos com óleos e solventes podem sofrer combustão espontânea e exigem recipientes corta-chamas específicos para resíduos perigosos.",
    educationalObjective: "Cumprir as normas de prevenção contra princípios de incêndio e descarte de produtos químicos perigosos.",
  },

  // =========================================================================
  // QUIZ DE SEGURANÇA - NÍVEL DIFÍCIL (Tomada de decisão crítica, priorização de riscos)
  // =========================================================================
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Proteções Mecânicas & NR-12",
    question: "Durante a produção seriada, o intertravamento de segurança de uma porta de célula robotizada começa a falhar intermitentemente. Qual decisão deve ser tomada?",
    optionA: "Instalar um imã provisório para burlar o sensor e manter a meta de produção até o fim de semana",
    optionB: "Desligar e bloquear a célula imediatamente (LOTO), registrar Red Flag e só retomar após reparo e validação de segurança pela engenharia",
    optionC: "Pedir para o operador trabalhar com um braço esticado sem encostar na porta",
    optionD: "Reduzir a velocidade do robô em 20% mantendo a porta aberta",
    correctOption: "B",
    explanation: "Burlar ou operar com sistemas de segurança NR-12 danificados é infração gravíssima de segurança; a parada com LOTO é mandatória.",
    educationalObjective: "Garantir tolerância zero contra a burla de dispositivos de intertravamento e proteção mecânica.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Trabalho a Quente & Atmosferas Perigosas",
    question: "Uma manutenção emergencial exige solda em estrutura metálica a 8 metros de altura próxima a tubulações industriais. Quais requisitos prévios são mandatórios?",
    optionA: "Apenas autorização verbal do operador mais próximo e um balde com água no chão",
    optionB: "Emissão de Permissão de Trabalho a Quente e Trabalho em Altura (PT/PET), medição de gases, isolamento com mantas antichama, linha de vida e vigia de incêndio dedicado",
    optionC: "Realizar a solda o mais rápido possível para evitar que o calor se propague pelo ar",
    optionD: "Ligar ventiladores comuns de mesa soprando sobre a tubulação para dispersar faíscas",
    correctOption: "B",
    explanation: "Trabalhos a quente em altura combinam múltiplos riscos críticos que exigem autorização formal, retenção de fagulhas e monitoramento contínuo por vigia.",
    educationalObjective: "Aplicar o rigor procedimental em tarefas especiais de alto potencial de gravidade.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Emergência Química Complexa",
    question: "Ao romper-se uma tubulação industrial de fluido de corte aquecido na fábrica, atingindo dois colaboradores, qual é a prioridade número 1 da equipe de resposta?",
    optionA: "Pegar o telefone e postar um aviso no grupo de mensagens da empresa",
    optionB: "Conduzir os atingidos imediatamente ao chuveiro de emergência/lava-olhos por 15 minutos, isolar a fonte com LOTO e acionar brigada médica com a FISPQ em mãos",
    optionC: "Tentar limpar o chão primeiro com estopas para não manchar o piso epóxi",
    optionD: "Aplicar pomadas caseiras e mandar os colaboradores continuarem operando a máquina",
    correctOption: "B",
    explanation: "A lavagem contínua abundante é vital para evitar queimaduras químicas profundas, simultaneamente à contenção da fonte e suporte médico com identificação do produto.",
    educationalObjective: "Priorizar a vida e a descontaminação imediata em acidentes químicos graves.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Intervenção Elétrica & Arco Elétrico",
    question: "Ao abrir um painel de distribuição trifásico para diagnóstico elétrico, quais medidas são legal e tecnicamente exigidas antes de qualquer toque?",
    optionA: "Utilizar calçado de borracha comum e encostar a ponta da chave de fenda para verificar se faísca",
    optionB: "Profissional qualificado/autorizado NR-10, uso de vestimenta antichama (ATPV compatível), luvas de borracha isolante com sobreluva e teste de ausência de tensão com instrumento aferido",
    optionC: "Apenas pedir para os operadores ao lado darem um passo para trás",
    optionD: "Desligar o disjuntor geral da fábrica inteira sem autorização da subestação",
    correctOption: "B",
    explanation: "O risco de choque elétrico e arco voltaico requer qualificação formal NR-10, EPIs com classificação térmica adequada e aferição comprovada de energia zero.",
    educationalObjective: "Reconhecer os perigos invisíveis de arcos elétricos e respeitar o controle de energia elétrica.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Priorização de Riscos Múltiplos",
    question: "Em uma mesma área, você observa: 1) poça de óleo na faixa de pedestres; 2) trabalhador sem óculos manuseando esmeril; 3) empilhadeira manobrando de ré com aviso sonoro inoperante. Qual deve ser a prioridade de contenção imediata?",
    optionA: "Avisar o setor financeiro sobre o custo do óleo derramado",
    optionB: "Interromper imediatamente a operação do esmeril e a manobra da empilhadeira (riscos iminentes a pessoas), sinalizando a poça em seguida para limpeza",
    optionC: "Limpar o óleo primeiro, pois a sujeira visual é mais fácil de notar",
    optionD: "Esperar acontecer um incidente para saber qual era o perigo mais crítico",
    correctOption: "B",
    explanation: "Na hierarquia de priorização de riscos, condições com potencial iminente de cegueira ou esmagamento/morte sobrepõem-se à limpeza do piso, que deve ser isolado.",
    educationalObjective: "Capacitar a tomada de decisão rápida e lógica frente a múltiplos riscos simultâneos.",
  },
  {
    gameType: "quiz_seguranca",
    difficulty: "dificil",
    theme: "Investigação & Causa-Raiz",
    question: "Após a ocorrência de um quase-acidente na linha, qual abordagem na investigação garante que o evento nunca mais se repita?",
    optionA: "Focar em apontar um culpado para adverti-lo formalmente na frente da equipe",
    optionB: "Aplicar metodologia de causa-raiz (como 5 Porquês ou Diagrama de Ishikawa), corrigindo falhas de processo, engenharia e padrões de trabalho",
    optionC: "Arquivar o caso sem mudanças para não gerar retrabalho nos relatórios",
    optionD: "Apenas pintar mais uma faixa amarela no chão sem analisar por que a falha aconteceu",
    correctOption: "B",
    explanation: "A verdadeira cultura de segurança investiga as causas sistêmicas e os controles de engenharia, e não a culpa individual, eliminando o risco definitivamente.",
    educationalObjective: "Promover a mentalidade de melhoria contínua através da análise de causa-raiz em SST.",
  },

  // =========================================================================
  // QUIZ DE ERGONOMIA - NÍVEL FÁCIL (Noções básicas, postura, ajustes diretos)
  // =========================================================================
  {
    gameType: "quiz_ergonomia",
    difficulty: "facil",
    theme: "Ergonomia • Postura & Zona de Alcance",
    question: "Qual é o princípio fundamental da 'Zona de Alcance Ótimo' na bancada de trabalho?",
    optionA: "Manter ferramentas e peças de uso constante próximas ao corpo, na altura do cotovelo, sem exigir torção do tronco",
    optionB: "Colocar as peças mais usadas o mais longe possível para forçar alongamentos contínuos",
    optionC: "Pendurar ferramentas acima da cabeça para liberar totalmente o tampo da mesa",
    optionD: "Guardar todos os materiais no chão embaixo da bancada",
    correctOption: "A",
    explanation: "Itens mantidos na zona de alcance ótimo evitam extensão excessiva de braços, rotação da coluna e sobrecarga nos ombros.",
    educationalObjective: "Identificar e configurar a zona de alcance confortável no posto de montagem.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "facil",
    theme: "Ergonomia • Levantamento e Movimentação de Peso",
    question: "Ao levantar manualmente uma caixa de componentes do piso, qual é a postura correta e segura para a coluna?",
    optionA: "Manter as pernas retas e dobrar a coluna para a frente em arco",
    optionB: "Flexionar os joelhos, manter a coluna alinhada, segurar a carga firme junto ao corpo e levantar usando a força das pernas",
    optionC: "Girar o tronco para o lado enquanto ergue o peso do chão",
    optionD: "Pegar a carga apenas com as pontas dos dedos e os braços esticados",
    correctOption: "B",
    explanation: "As pernas possuem músculos muito mais fortes que a lombar. Manter a carga junto ao corpo reduz o efeito de alavanca sobre as vértebras.",
    educationalObjective: "Praticar a técnica segura de levantamento manual de cargas.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "facil",
    theme: "Ergonomia • Pausas Ativas & Fadiga",
    question: "Qual é a função das pequenas pausas ativas e da ginástica laboral na rotina fabril da CDBS?",
    optionA: "Aumentar a lentidão dos processos para reduzir o ritmo da fábrica",
    optionB: "Aliviar a tensão muscular, estimular a circulação sanguínea e compensar grupos musculares exigidos na tarefa",
    optionC: "Substituir o uso de EPIs e equipamentos ergonômicos de apoio",
    optionD: "Permitir que os operadores fiquem sentados sem se movimentar o dia inteiro",
    correctOption: "B",
    explanation: "Pausas ativas e alongamentos compensatórios combatem a fadiga muscular precoce e previnem o desenvolvimento de lesões crônicas.",
    educationalObjective: "Valorizar e cumprir as pausas ergonômicas ativas como ferramenta preventiva de saúde.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "facil",
    theme: "Ergonomia • Reconhecimento e Saúde Ocupacional",
    question: "Se você começar a sentir formigamento, queimação ou dor constante nos punhos durante a montagem repetitiva, o que deve fazer?",
    optionA: "Tomar analgésicos por conta própria todos os dias e esconder o sintoma para não preocupar ninguém",
    optionB: "Informar a liderança e a equipe de ergonomia/saúde ocupacional precocemente para avaliar o posto e a pega da ferramenta",
    optionC: "Forçar os movimentos com mais velocidade para que o tendão se acostume com a dor",
    optionD: "Trocar de luva por uma bem apertada para imobilizar totalmente os dedos",
    correctOption: "B",
    explanation: "O relato precoce de sintomas evita que um simples desconforto muscular evolua para uma tendinite crônica ou síndrome do túnel do carpo.",
    educationalObjective: "Estimular o autocuidado e o encaminhamento precoce a serviços de saúde ocupacional.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "facil",
    theme: "Ergonomia • Postura Estática & Alternância",
    question: "Para atividades que exigem permanecer muito tempo em pé no posto de trabalho, qual recurso ajuda a diminuir a sobrecarga nas pernas e na lombar?",
    optionA: "Trabalhar descalço no concreto puro",
    optionB: "Uso de tapete antifadiga, apoio para alternância de pés e calçados com bom amortecimento",
    optionC: "Permanecer totalmente imóvel como uma estátua durante todo o expediente",
    optionD: "Apoiar todo o peso do corpo sempre no mesmo calcanhar",
    correctOption: "B",
    explanation: "Tapetes antifadiga e apoios para alternância dos pés promovem micromovimentos musculares que ativam a circulação e reduzem a fadiga lombar.",
    educationalObjective: "Adotar recursos físicos e de alternância postural para amenizar a carga estática em pé.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "facil",
    theme: "Ergonomia • Posto Informatizado e Postura",
    question: "Ao utilizar terminais de computador, notebooks ou monitores na gestão operacional, qual é o alinhamento ergonômico correto da tela?",
    optionA: "A tela deve ficar bem no chão para olhar para baixo dobrando o pescoço",
    optionB: "A borda superior da tela deve ficar na altura dos olhos e a uma distância de aproximadamente um braço estendido",
    optionC: "O monitor deve ficar virado de lado, exigindo que o pescoço fique sempre torcido",
    optionD: "A tela deve ficar colada no nariz do operador em ambiente totalmente escuro",
    correctOption: "B",
    explanation: "O topo do monitor alinhado aos olhos mantém a coluna cervical neutra, prevenindo dores de cabeça e tensões no trapézio.",
    educationalObjective: "Configurar corretamente a estação de trabalho informatizada e displays operacionais.",
  },

  // =========================================================================
  // QUIZ DE ERGONOMIA - NÍVEL MÉDIO (Antropometria, ferramentas, esforço repetitivo)
  // =========================================================================
  {
    gameType: "quiz_ergonomia",
    difficulty: "medio",
    theme: "Ergonomia • Torque & Força de Reação",
    question: "Ao operar parafusadeiras pneumáticas de alto torque na montagem de eixos pesados, qual dispositivo evita que o tranco seja absorvido pelo punho do operador?",
    optionA: "Apertar o gatilho com as duas mãos e travar o punho com toda a força do corpo",
    optionB: "Utilização de braço de reação de torque articulado ou barra telescópica de ancoragem",
    optionC: "Aumentar a pressão de ar para que o parafuso aperte num microssegundo",
    optionD: "Desativar o limitador de embreagem da parafusadeira",
    correctOption: "B",
    explanation: "Braços articulados de reação absorvem o impacto mecânico do torque final, protegendo as articulações do punho, cotovelo e ombro.",
    educationalObjective: "Reconhecer a necessidade e o uso correto de braços de reação de torque em ferramentas industriais.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "medio",
    theme: "Ergonomia • Dispositivos Mecânicos de Apoio e Movimentação",
    question: "Na retirada de componentes pesados posicionados no fundo de paletes ou caçambas profundas, qual solução ergonômica previne sobrecarga na coluna lombar?",
    optionA: "Debruçar o tronco por cima da grade da caçamba com os pés suspensos",
    optionB: "Utilizar mesas pantográficas basculantes ou elevadores de caçamba que aproximam o material da altura da cintura",
    optionC: "Pular para dentro da caçamba e jogar as peças para cima",
    optionD: "Pedir para alguém menor e mais leve entrar na caçamba",
    correctOption: "B",
    explanation: "Mesas basculantes e elevadores mantêm o trabalho dentro da faixa neutra de altura, evitando flexão profunda e compressão discal excessiva.",
    educationalObjective: "Priorizar dispositivos mecânicos de elevação e basculamento em substituição à flexão extrema de coluna.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "medio",
    theme: "Ergonomia • Repetitividade, Pausas e Rotação de Tarefas",
    question: "Em uma linha de montagem de alto ritmo, qual é o principal benefício da rotação planejada de postos entre diferentes operações ao longo do turno?",
    optionA: "Fazer com que o operador esqueça como fazer a primeira atividade",
    optionB: "Alternar os grupos musculares e articulações exigidos, reduzindo a sobrecarga contínua e a monotonia postural",
    optionC: "Eliminar a necessidade de treinamento nos procedimentos operacionais",
    optionD: "Aumentar o cansaço dos colaboradores fazendo-os caminhar mais pela fábrica",
    correctOption: "B",
    explanation: "O rodízio ergonômico evita o estresse acumulado sobre o mesmo tendão ou articulação, prevenindo LER/DORT por repetição.",
    educationalObjective: "Compreender a lógica fisiológica da alternância e rotação de postos de trabalho.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "medio",
    theme: "Ergonomia • Iluminação & Conforto Visual",
    question: "Na inspeção de qualidade visual de engrenagens e rolamentos com superfícies metálicas brilhantes, qual fator ergonômico deve ser controlado?",
    optionA: "Apagar todas as luzes para criar contraste no escuro",
    optionB: "Evitar reflexos e ofuscamento direto nos olhos, garantindo iluminação difusa adequada sem sombras fortes sobre a peça",
    optionC: "Usar lâmpadas que pisquem em alta frequência para testar os reflexos visuais",
    optionD: "Colocar holofotes de alta potência apontados diretamente para a face do inspetor",
    correctOption: "B",
    explanation: "O ofuscamento e reflexos em metais exigem posicionamento difuso das fontes de luz para evitar fadiga ocular e tensão cervical compensatória.",
    educationalObjective: "Ajustar condições ambientais de iluminação para proteger o conforto visual e postural.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "medio",
    theme: "Ergonomia • Pega e Postura Neutra em Ferramentas",
    question: "Ao selecionar uma ferramenta manual para aperto repetitivo em bancada vertical versus horizontal, o que determina a escolha entre empunhadura reta ou pistola?",
    optionA: "A cor do cabo e o peso aparente da ferramenta na caixa",
    optionB: "A geometria que permita manter o punho na posição neutra (reto, como em aperto de mão), sem desvios ulnar ou radial forçados",
    optionC: "A ferramenta mais barata disponível no catálogo de compras",
    optionD: "Sempre usar a empunhadura pistola, mesmo que force o punho para cima a 90 graus",
    correctOption: "B",
    explanation: "A ferramenta ergonômica é aquela que se adapta à tarefa mantendo o punho alinhado à musculatura do antebraço sem torções.",
    educationalObjective: "Escolher a geometria de ferramenta adequada ao plano de trabalho preservando o alinhamento articular.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "medio",
    theme: "Ergonomia • Movimentação de Cargas em Equipe",
    question: "Quando duas pessoas realizam o transporte manual combinado de uma peça estrutural longa de 40 kg, qual regra garante a segurança de ambos?",
    optionA: "Um colaborador puxa para a frente de costas e o outro empurra sem comunicação",
    optionB: "Definir um líder para comandar a contagem do levantamento simultâneo, manter a mesma altura de transporte e combinar o momento da descida",
    optionC: "Soltar a peça imediatamente se sentir cansaço sem avisar o parceiro",
    optionD: "Cada um andar em um ritmo diferente para terminar mais rápido",
    correctOption: "B",
    explanation: "O trabalho em equipe exige sincronismo e comunicação clara; se um colaborador solta ou hesita repentinamente, toda a carga sobrecarrega a coluna do outro.",
    educationalObjective: "Aplicar protocolos de sincronização e comunicação clara em movimentações manuais compartilhadas.",
  },

  // =========================================================================
  // QUIZ DE ERGONOMIA - NÍVEL DIFÍCIL (Biomecânica avançada, análise de riscos, NR-17)
  // =========================================================================
  {
    gameType: "quiz_ergonomia",
    difficulty: "dificil",
    theme: "Ergonomia • Biomecânica da Coluna e Postura sob Carga",
    question: "Qual é a consequência biomecânica sobre os discos intervertebrais quando um trabalhador ergue uma carga pesada combinando flexão e torção do tronco?",
    optionA: "A pressão intradiscal diminui porque o movimento distribui a carga por mais músculos",
    optionB: "Ocorre cisalhamento assimétrico e compressão extrema no anel fibroso, aumentando drasticamente o risco de fissura discal e hérnia lombar",
    optionC: "Os discos ganham maior flexibilidade e resistência a longo prazo",
    optionD: "Não há impacto nas vértebras, pois os ligamentos da coluna suportam forças de rotação sem deformação",
    correctOption: "B",
    explanation: "A combinação de flexão anterior com rotação axial é o vetor mecânico mais lesivo para o disco intervertebral, multiplicando a tensão cisalhante sobre as fibras.",
    educationalObjective: "Compreender os mecanismos biomecânicos críticos de lesão discal para eliminar torções de tronco sob carga.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "dificil",
    theme: "Ergonomia • Vibração Ocupacional e Saúde",
    question: "Ao operar empilhadeiras em pisos irregulares ou utilizar chaves de impacto pneumáticas de alto impacto por horas consecutivas, quais riscos ocupacionais devem ser monitorados?",
    optionA: "Apenas perda de apetite e irritação no couro cabeludo",
    optionB: "Síndrome da vibração de mãos e braços (dedo branco/Raynaud) em ferramentas manuais e distúrbios osteomusculares na coluna por vibração de corpo inteiro",
    optionC: "Melhora instantânea do tônus muscular dos membros superiores",
    optionD: "Aumento da temperatura corporal sem qualquer efeito nas articulações",
    correctOption: "B",
    explanation: "A vibração mecânica contínua danifica microcapilares e terminações nervosas dos dedos, além de acelerar a degeneração dos discos da coluna vertebral.",
    educationalObjective: "Identificar os efeitos crônicos da exposição ocupacional a vibrações localizadas e de corpo inteiro.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "dificil",
    theme: "Ergonomia • Análise Ergonômica do Trabalho (AET / NR-17)",
    question: "Em um posto de abastecimento onde operadores relatam desconforto nas costas, a chefia propõe comprar cintas lombares para todos. De acordo com a NR-17 e a boa prática ergonômica, qual é a avaliação correta?",
    optionA: "A cinta lombar é a melhor solução e substitui qualquer mudança de engenharia no posto",
    optionB: "A cinta lombar não é EPI regulamentado, pode atrofiar a musculatura estabilizadora abdominal e a prioridade deve ser redesenhar a altura do posto e usar talhas",
    optionC: "Deve-se exigir que os operadores usem duas cintas sobrepostas para aumentar a rigidez",
    optionD: "Cintas lombares curam hérnias de disco pré-existentes na operação",
    correctOption: "B",
    explanation: "Cintas lombares criam falsa sensação de segurança e enfraquecem o 'core'; a prioridade normativa é a eliminação do esforço através de melhorias de engenharia e layout.",
    educationalObjective: "Aplicar a hierarquia de controles da NR-17 contra soluções paliativas ineficazes de proteção postural.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "dificil",
    theme: "Ergonomia • Movimentação de Cargas e Equação de NIOSH",
    question: "Pela metodologia de levantamento manual de cargas (Equação de NIOSH), quais variáveis reduzem mais severamente o limite de peso seguro recomendado para um levantamento?",
    optionA: "A marca do uniforme e a cor da caixa transportada",
    optionB: "A grande distância horizontal da carga em relação ao corpo, a frequência elevada de repetições e a assimetria/torção no movimento",
    optionC: "A altura da sala e a ventilação do corredor distante",
    optionD: "O material do piso se a distância percorrida for menor que 50 centímetros",
    correctOption: "B",
    explanation: "Na fórmula de NIOSH, quanto mais longe a carga estiver do centro de gravidade do corpo e quanto maior a torção e a frequência, menor é o peso admissível.",
    educationalObjective: "Compreender os multiplicadores críticos que influenciam o limite de peso seguro segundo a metodologia NIOSH.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "dificil",
    theme: "Ergonomia • Carga Cognitiva e Saúde Ocupacional",
    question: "Em células robotizadas de alta tecnologia na montagem de motores Euro VI, como a sobrecarga cognitiva e o estresse por ritmo excessivo afetam a segurança física?",
    optionA: "Não afetam em nada, pois ergonomia se restringe apenas ao peso das caixas",
    optionB: "A fadiga mental reduz a atenção seletiva, lentifica o tempo de reação, induz a omissão de checagens críticas e aumenta o índice de acidentes graves",
    optionC: "Aumenta a precisão das operações porque o cérebro trabalha mais rápido sob pressão extrema",
    optionD: "Elimina a necessidade de pausas durante a jornada de trabalho",
    correctOption: "B",
    explanation: "A ergonomia cognitiva estuda a interação humana com sistemas complexos. A sobrecarga mental e ritmo implacável levam ao erro de julgamento e incidentes graves.",
    educationalObjective: "Integrar aspectos cognitivos e psicofisiológicos na prevenção de acidentes industriais em sistemas automatizados.",
  },
  {
    gameType: "quiz_ergonomia",
    difficulty: "dificil",
    theme: "Ergonomia • Planejamento Participativo e Saúde",
    question: "Ao projetar uma nova linha de pré-montagem na CDBS Osasco, qual estratégia ergonômica garante o melhor resultado prático de adaptação às pessoas?",
    optionA: "Comprar equipamentos prontos sem consultar quem opera na bancada diariamente",
    optionB: "Ergonomia participativa: envolver operadores, liderança, engenharia e SESMT desde a fase de projeto e simulação de protótipos de postos (maquetes/mockups)",
    optionC: "Copiar exatamente as medidas de uma fábrica de automóveis de outro país com perfis físicos diferentes",
    optionD: "Esperar a linha operar por um ano para verificar onde as lesões aparecem",
    correctOption: "B",
    explanation: "A ergonomia participativa aproveita a experiência real de quem opera, garantindo validação antropométrica, fluxo suave e eliminação de riscos antes do início da produção.",
    educationalObjective: "Promover a metodologia de ergonomia participativa e cocriação de postos seguros.",
  },
];
