export const INITIAL_SECURITY_QUESTIONS = [
  {
    gameType: "quiz_seguranca" as const,
    question: "Qual é a atitude correta e imediata ao identificar uma condição de risco (Red Flag) na fábrica?",
    optionA: "Continuar trabalhando e avisar a liderança apenas no final do expediente",
    optionB: "Parar a atividade, sinalizar/isolar a área se aplicável e comunicar imediatamente o risco",
    optionC: "Aguardar outro colega com mais tempo de casa notar o problema",
    optionD: "Tentar consertar máquinas elétricas por conta própria sem desenergização",
    correctOption: "B" as const,
    explanation: "Na cultura Cummins, ao ver um risco você deve parar, comunicar e agir com segurança antes que ocorra um incidente.",
    theme: "Red Flag & Comunicação de Risco",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Antes de realizar manutenção em motores ou linhas automatizadas, qual procedimento de energia zero é obrigatório?",
    optionA: "Apenas desligar o botão liga/desliga do painel local",
    optionB: "Avisar o operador ao lado verbalmente e trabalhar rápido",
    optionC: "Bloqueio e Etiquetagem (LOTO - Lockout & Tagout) com teste de energia residual",
    optionD: "Retirar o fusível com a mão sem equipamento de proteção",
    correctOption: "C" as const,
    explanation: "O processo LOTO garante isolamento confiável de todas as fontes de energia perigosa antes da intervenção.",
    theme: "Bloqueio e Etiquetagem",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Ao transitar pelas áreas operacionais e de montagem da fábrica, qual conduta referente a EPIs é obrigatória?",
    optionA: "Usar óculos de segurança com proteção lateral e calçado com biqueira em todas as faixas operacionais",
    optionB: "Usar óculos somente se houver faíscas visíveis no momento",
    optionC: "Tirar o protetor auricular sempre que quiser conversar com um colega",
    optionD: "Andar pelas faixas de empilhadeira para encurtar caminho",
    correctOption: "A" as const,
    explanation: "EPIs básicos como calçado de segurança e óculos com proteção lateral são regras fundamentais para circulação fabril.",
    theme: "EPIs",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "O que deve ser verificado antes de utilizar um extintor de incêndio em um princípio de fogo industrial?",
    optionA: "Se o extintor está pintado com tinta brilhante recente",
    optionB: "A classe do fogo (A, B ou C), o manômetro na faixa verde e a desobstrução do acesso",
    optionC: "Se há água na mangueira mesmo sendo quadro elétrico energizado",
    optionD: "Apenas a cor do lacre de plástico",
    correctOption: "B" as const,
    explanation: "A classe do fogo e a pressão no manômetro determinam o agente extintor correto para não agravar o incêndio.",
    theme: "Procedimentos de Emergência",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Qual é o objetivo principal da campanha Red Flag na unidade Cummins?",
    optionA: "Punir operadores que relatam problemas nas linhas de motores",
    optionB: "Interromper e relatar condições ou atos inseguros antes que se transformem em acidentes",
    optionC: "Apenas registrar estatísticas sem ação de correção em chão de fábrica",
    optionD: "Aumentar a velocidade das linhas sacrificando regras operacionais",
    correctOption: "B" as const,
    explanation: "A Red Flag empodera qualquer colaborador a pausar a operação e comunicar riscos para correção preventiva.",
    theme: "Red Flag",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Em relação ao tráfego de empilhadeiras e rebocadores industriais na planta, qual regra de ouro deve ser seguida?",
    optionA: "O pedestre sempre tem a preferência absoluta em cruzamentos cegos sem olhar",
    optionB: "Respeitar as faixas de pedestre pintadas, manter contato visual com o operador e parar nos cruzamentos sinalizados",
    optionC: "Caminhar olhando o celular desde que dentro da faixa amarela",
    optionD: "Subir no garfo da empilhadeira para alcançar peças altas na estante",
    correctOption: "B" as const,
    explanation: "O contato visual e o respeito à sinalização física evitam atropelamentos e colisões com máquinas em manobra.",
    theme: "Sinalização e Circulação",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Qual é a postura ergonômica adequada ao levantar manualmente uma caixa de componentes pesados do chão?",
    optionA: "Manter as pernas retas e curvar a coluna lombar para baixo",
    optionB: "Flexionar os joelhos, manter a carga próxima ao corpo e manter a coluna ereta",
    optionC: "Girar o tronco bruscamente enquanto faz a força de elevação",
    optionD: "Levantar caixas acima de 25 kg sozinho sem solicitar auxílio mecânico",
    correctOption: "B" as const,
    explanation: "Flexionar os joelhos e aproximar a carga do centro de gravidade protege a coluna lombar contra lesões musculoesqueléticas.",
    theme: "Ergonomia",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Quando uma proteção física móvel de máquina (intertravamento) estiver danificada ou desregulada, o que fazer?",
    optionA: "Burlar o sensor com fita para não parar a meta da linha",
    optionB: "Operar com cuidado redobrado sem avisar a manutenção",
    optionC: "Parar a máquina, etiquetar como inoperante e acionar manutenção/segurança",
    optionD: "Remover a proteção para facilitar o acesso às ferramentas",
    correctOption: "C" as const,
    explanation: "Dispositivos de proteção nunca podem ser burlados; falhas exigem paralisação preventiva imediata.",
    theme: "Máquinas e Proteções",
    difficulty: "dificil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Durante o uso de produtos químicos para lavagem ou desengraxe de peças de motor, qual item é indispensável?",
    optionA: "Consultar a FISPQ/FDS e utilizar luvas químicas, óculos adequados e ventilação",
    optionB: "Cheirar o produto de perto para verificar se ainda está ativo",
    optionC: "Armazenar restos em garrafas plásticas de refrigerante sem rótulo",
    optionD: "Misturar solventes diferentes para aumentar a potência de limpeza",
    correctOption: "A" as const,
    explanation: "A Ficha de Dados de Segurança (FISPQ/FDS) orienta o manuseio seguro, EPIs adequados e primeiros socorros.",
    theme: "Riscos Industriais & Químicos",
    difficulty: "dificil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "O que caracteriza o 'Comportamento Seguro' de uma equipe industrial de alto desempenho?",
    optionA: "Cuidar apenas de si mesmo e ignorar se o colega ao lado estiver sem proteção",
    optionB: "Cuidado ativo: cuidar de si, cuidar do colega e aceitar intervenções seguras",
    optionC: "Apressar tarefas ignorando o checklist de pré-operação",
    optionD: "Relatar quase-acidentes apenas se envolver dano financeiro alto",
    correctOption: "B" as const,
    explanation: "O cuidado ativo constrói uma cultura onde todos se sentem responsáveis pelo retorno seguro de todos para casa.",
    theme: "Comportamento Seguro",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Em caso de acionamento do alarme geral de emergência e evacuação na fábrica, qual é o procedimento correto?",
    optionA: "Correr desesperadamente para o estacionamento pegar o carro",
    optionB: "Interromper atividades em segurança, seguir rotas de fuga sinalizadas e ir ao Ponto de Encontro",
    optionC: "Voltar para o vestiário para pegar mochilas e pertences pessoais",
    optionD: "Subir no telhado para filmar a ocorrência com o smartphone",
    correctOption: "B" as const,
    explanation: "Evacuações exigem calma, rotas desobstruídas e contagem de presença no Ponto de Encontro predeterminado.",
    theme: "Procedimentos de Emergência",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Como o programa 5S contribui diretamente para a prevenção de acidentes na manufatura?",
    optionA: "Serve apenas para deixar o piso encerado para visitas de clientes",
    optionB: "Elimina obstáculos nas rotas, previne tropeços, identifica vazamentos rapidamente e organiza ferramentas",
    optionC: "Substitui a necessidade de utilizar equipamentos de proteção individual",
    optionD: "Reduz o tempo de descanso legal dos colaboradores da planta",
    correctOption: "B" as const,
    explanation: "Ambientes limpos e organizados revelam anomalias, eliminam riscos de tropeço/queda e otimizam a segurança.",
    theme: "Segurança Industrial & 5S",
    difficulty: "medio" as const,
  },
];

export const INITIAL_ERGONOMICS_QUESTIONS = Array.from({ length: 12 }, () => ({ gameType: "quiz_ergonomia" as const }));

export const INITIAL_GAME_SETTINGS = [
  {
    gameKey: "quiz_seguranca",
    title: "SIPATMA CDBS • Segurança",
    description: "Perguntas sobre segurança, prevenção de acidentes e rotina operacional da unidade Cummins Osasco.",
    active: true,
  },
  {
    gameKey: "quiz_ergonomia",
    title: "SIPATMA CDBS • Ergonomia",
    description: "Desafios sobre postura, movimentação, pausas e saúde ocupacional na rotina CDBS.",
    active: true,
  },
  {
    gameKey: "ache_o_erro",
    title: "SIPATMA CDBS • Ache o Erro",
    description: "Inspecione cenários de oficina, montagem, fábrica e apoio administrativo para encontrar atos inseguros.",
    active: true,
  },
  {
    gameKey: "organize_a_fabrica",
    title: "SIPATMA CDBS • Organize a Fábrica",
    description: "Aplique 5S e organização visual para deixar o ambiente Cummins Osasco mais seguro e eficiente.",
    active: true,
  },
];


export const CDBS_SPOT_ERROR_SCENARIOS = [
  { key: "cdbs-v4-montagem-2026", label: "Fase 1 • Montagem • Nova temporada CDBS", image: "/manus-storage/montagem-errors_69a82e1a.png", safeImage: "/manus-storage/montagem-safe_3568b2c0.png" },
  { key: "cdbs-v4-logistica-2026", label: "Fase 2 • Logística • Nova temporada CDBS", image: "/manus-storage/logistica-errors_98f26e91.png", safeImage: "/manus-storage/logistica-safe_dda0c67f.png" },
  { key: "cdbs-v4-manutencao-2026", label: "Fase 3 • Manutenção • Nova temporada CDBS", image: "/manus-storage/manutencao-errors_cdcbc989.png", safeImage: "/manus-storage/manutencao-safe_06f85285.png" },
  { key: "cdbs-v4-almoxarifado-2026", label: "Fase 4 • Almoxarifado • Nova temporada CDBS", image: "/manus-storage/almoxarifado-errors_3feeb25f.png", safeImage: "/manus-storage/almoxarifado-safe_06d9ed7a.png" },
  { key: "cdbs-v4-producao-2026", label: "Fase 5 • Produção • Nova temporada CDBS", image: "/manus-storage/producao-errors_d29da817.png", safeImage: "/manus-storage/producao-safe_1d965c14.png" },
] as const;

export const V4_CDBS_SPOT_ERROR_HOTSPOTS = [
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Óculos fora da posição", description: "A proteção ocular foi levantada durante a montagem; mantenha os óculos sobre os olhos em toda atividade com risco de projeção.", hint: "Observe o rosto do trabalhador à esquerda.", category: "EPI", x: 35, y: 21, width: 12, height: 8, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Cabo na rota amarela", description: "O cabo da ferramenta atravessa a rota de pedestres e cria risco de tropeço.", hint: "Acompanhe o cabo desde a ferramenta até o piso.", category: "Circulação", x: 39, y: 80, width: 27, height: 9, tolerance: 2, shape: "poligono", points: JSON.stringify([{x:25,y:78},{x:53,y:73},{x:70,y:82},{x:64,y:90},{x:40,y:86}]) },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Derramamento sob o suporte", description: "O óleo no piso deve ser contido, sinalizado e limpo antes de liberar a área.", hint: "Procure uma condição escorregadia próxima ao motor.", category: "Químico", x: 58, y: 91, width: 17, height: 7, tolerance: 2, shape: "poligono", points: JSON.stringify([{x:50,y:89},{x:68,y:88},{x:75,y:94},{x:58,y:98},{x:48,y:94}]) },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Chave no piso", description: "Ferramentas deixadas na passagem podem causar tropeço e devem retornar ao painel ou bancada.", hint: "Verifique a faixa livre à direita.", category: "5S", x: 91, y: 91, width: 9, height: 5, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Portão de proteção aberto", description: "A proteção perimetral deve permanecer fechada para impedir acesso à zona de risco.", hint: "Observe o portão amarelo no fundo.", category: "Máquinas", x: 88, y: 35, width: 10, height: 28, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Caixa sobrecarregada", description: "A caixa de componentes está acima de uma condição estável e pode derrubar peças.", hint: "Compare o carrinho de peças com a cena segura.", category: "Armazenagem", x: 18, y: 48, width: 17, height: 18, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Mão sem luva na zona de trabalho", description: "A mão exposta não oferece proteção adequada contra bordas e contato com componentes.", hint: "Observe a mão da trabalhadora à direita.", category: "EPI", x: 69, y: 42, width: 7, height: 8, tolerance: 2, shape: "circulo" },

  { scenarioKey: "cdbs-v4-logistica-2026", title: "Pallet inclinado", description: "A carga inclinada pode tombar e atingir pessoas ou bloquear a circulação.", hint: "Compare o pallet alto no lado esquerdo.", category: "Armazenagem", x: 26, y: 38, width: 23, height: 31, tolerance: 2, shape: "poligono", points: JSON.stringify([{x:13,y:25},{x:39,y:20},{x:48,y:55},{x:26,y:66},{x:13,y:56}]) },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Filme plástico solto", description: "O filme plástico arrastando para a rota pode provocar tropeço e perda de controle da carga.", hint: "Siga a borda do pallet até o corredor.", category: "5S", x: 46, y: 56, width: 20, height: 17, tolerance: 2, shape: "poligono", points: JSON.stringify([{x:38,y:50},{x:52,y:51},{x:62,y:67},{x:45,y:69},{x:36,y:58}]) },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Pedestre fora da faixa", description: "A circulação de pedestres deve ocorrer dentro da rota segregada e demarcada.", hint: "Observe a posição dos pés do trabalhador.", category: "Circulação", x: 65, y: 49, width: 12, height: 31, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Garfo avançado no corredor", description: "Os garfos do equipamento móvel devem ficar recolhidos e dentro da baia quando estacionado.", hint: "Olhe a parte inferior da paleteira.", category: "Movimentação", x: 33, y: 75, width: 27, height: 11, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Caixa para fora do rack", description: "Materiais projetados para fora do rack podem cair e atingir quem circula.", hint: "Observe a estante azul à direita.", category: "Armazenagem", x: 91, y: 30, width: 10, height: 15, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Colete de alta visibilidade ausente", description: "A visibilidade do pedestre é essencial em áreas com movimentação de equipamentos.", hint: "Compare a roupa do trabalhador com a cena segura.", category: "EPI", x: 65, y: 26, width: 16, height: 17, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Contentor na rota", description: "O contentor azul foi deixado na faixa de pedestres e reduz a passagem segura.", hint: "Examine o centro da faixa amarela.", category: "Circulação", x: 65, y: 78, width: 14, height: 11, tolerance: 2, shape: "retangulo" },

  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Cadeado de bloqueio ausente", description: "Toda fonte isolada deve permanecer bloqueada individualmente durante a manutenção.", hint: "Conte os cadeados no painel vermelho.", category: "LOTO", x: 51, y: 28, width: 8, height: 10, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Etiqueta de bloqueio no piso", description: "A etiqueta deve estar presa ao ponto de isolamento, nunca solta no equipamento.", hint: "Observe a parte baixa da máquina.", category: "LOTO", x: 76, y: 58, width: 12, height: 8, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Mão sem luva", description: "A luva adequada protege contra arestas, sujeira e contato com componentes.", hint: "Observe a mão do técnico junto ao painel.", category: "EPI", x: 72, y: 37, width: 8, height: 8, tolerance: 2, shape: "circulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Chave na borda", description: "Ferramentas na borda podem cair, danificar a máquina ou atingir alguém.", hint: "Examine a abertura da máquina.", category: "Ferramentas", x: 84, y: 62, width: 11, height: 9, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Cabo atravessando o piso", description: "O cabo deve ser conduzido por rota protegida para evitar tropeços.", hint: "Siga o cabo escuro sobre o piso.", category: "Circulação", x: 48, y: 79, width: 35, height: 9, tolerance: 2, shape: "poligono", points: JSON.stringify([{x:25,y:72},{x:54,y:75},{x:77,y:80},{x:74,y:87},{x:47,y:82},{x:24,y:79}]) },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Porta da máquina aberta", description: "A intervenção deve ocorrer com a máquina parada, isolada e com a proteção fechada quando aplicável.", hint: "Observe a porta transparente da máquina.", category: "Máquinas", x: 86, y: 28, width: 17, height: 37, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Vazamento no piso", description: "O fluido deve ser contido e o local sinalizado para evitar escorregamento.", hint: "Procure uma área brilhante junto à máquina.", category: "Químico", x: 82, y: 83, width: 20, height: 9, tolerance: 2, shape: "poligono", points: JSON.stringify([{x:72,y:78},{x:91,y:78},{x:96,y:88},{x:78,y:92},{x:69,y:86}]) },

  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Caixa acima da linha de carga", description: "A carga deve permanecer dentro do limite do rack para evitar queda de materiais.", hint: "Observe o nível superior do rack à direita.", category: "Armazenagem", x: 80, y: 18, width: 20, height: 14, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Caixa em queda", description: "Materiais não podem ficar projetados ou soltos em altura.", hint: "Procure um volume fora da prateleira.", category: "Armazenagem", x: 89, y: 37, width: 11, height: 15, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Trabalho sobre o último degrau", description: "O último degrau não deve ser usado como plataforma de trabalho; escolha acesso adequado.", hint: "Observe os pés do trabalhador.", category: "Ergonomia", x: 68, y: 47, width: 12, height: 12, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Caixa na faixa de circulação", description: "A faixa amarela precisa permanecer livre para circulação e evacuação.", hint: "Examine o piso no canto esquerdo.", category: "Circulação", x: 23, y: 82, width: 18, height: 15, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Fita pendurada no corredor", description: "Fitas e cintas soltas devem ser recolhidas para não enroscar em pessoas ou equipamentos.", hint: "Observe a lateral direita do rack.", category: "Organização", x: 95, y: 53, width: 5, height: 27, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Extintor com acesso bloqueado", description: "O acesso ao extintor deve permanecer totalmente desobstruído.", hint: "Compare a parede esquerda da cena.", category: "Emergência", x: 7, y: 55, width: 10, height: 18, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-almoxarifado-2026", title: "Contentor danificado", description: "Contentores rachados ou instáveis devem ser retirados de uso e substituídos.", hint: "Examine os bins na prateleira inferior.", category: "Armazenagem", x: 91, y: 80, width: 14, height: 12, tolerance: 2, shape: "retangulo" },

  { scenarioKey: "cdbs-v4-producao-2026", title: "Proteção da máquina aberta", description: "A proteção física deve impedir acesso à zona de movimento e permanecer fechada na operação.", hint: "Compare o painel transparente da máquina.", category: "Máquinas", x: 65, y: 28, width: 15, height: 38, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Óculos levantados", description: "Óculos de segurança levantados deixam os olhos expostos durante a atividade.", hint: "Observe o rosto da operadora.", category: "EPI", x: 37, y: 25, width: 9, height: 8, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Contentor na faixa", description: "O carrinho ocupa a faixa de pedestres e reduz a separação entre fluxo e processo.", hint: "Observe o carrinho azul junto à faixa.", category: "Circulação", x: 79, y: 54, width: 16, height: 24, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Peça no piso", description: "Componentes no piso criam risco de tropeço e devem retornar ao contentor.", hint: "Procure uma peça solta à frente da linha.", category: "5S", x: 50, y: 84, width: 8, height: 7, tolerance: 2, shape: "circulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Área vermelha ocupada", description: "A zona de emergência deve permanecer livre para acesso e intervenção rápida.", hint: "Examine a área vermelha ao lado direito.", category: "Emergência", x: 90, y: 83, width: 18, height: 18, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Alcance sobre a operação", description: "O operador não deve alcançar por cima ou dentro de área de movimento; use o procedimento seguro.", hint: "Observe a postura junto à bancada.", category: "Ergonomia", x: 44, y: 35, width: 14, height: 25, tolerance: 2, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Cobertura do transportador removida", description: "A cobertura protege contra pontos de esmagamento e deve estar instalada durante o funcionamento.", hint: "Compare o trecho inicial do transportador.", category: "Máquinas", x: 22, y: 42, width: 17, height: 18, tolerance: 2, shape: "retangulo" },
] as const;

export const INITIAL_CDBS_SPOT_ERROR_HOTSPOTS = [
  { scenarioKey: "cdbs-oficina-2026", title: "Óculos levantados durante a ferramenta", description: "O trabalhador está com proteção ocular fora da posição correta durante a atividade; o EPI deve proteger os olhos enquanto houver risco de projeção.", category: "EPI", x: 35, y: 17, width: 18, height: 38, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Cabo atravessando a passagem", description: "O cabo ocupa a rota amarela e pode causar tropeço; deve ser organizado ou protegido.", category: "Circulação", x: 52, y: 75, width: 38, height: 12, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Pano oleoso fora do recipiente", description: "Panos contaminados devem ir para recipiente apropriado, evitando contato e risco de incêndio.", category: "Químico", x: 91, y: 78, width: 15, height: 18, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Ferramenta na borda da bancada", description: "A ferramenta pode cair e atingir alguém; mantenha ferramentas em local estável e organizado.", category: "Organização", x: 16, y: 71, width: 18, height: 10, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Proteção da máquina aberta", description: "A proteção deve permanecer fechada durante a operação para impedir acesso à zona de perigo.", category: "Máquinas", x: 40, y: 35, width: 21, height: 44, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Levantamento com postura inadequada", description: "A carga deve ser aproximada do corpo, com joelhos flexionados e sem torção da coluna.", category: "Ergonomia", x: 51, y: 59, width: 18, height: 34, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Carga sem contenção no carrinho", description: "Componentes devem estar apoiados e contidos para não cair durante a movimentação.", category: "Movimentação", x: 73, y: 43, width: 20, height: 25, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Material invadindo a faixa", description: "A rota de pedestres deve permanecer livre e claramente separada das áreas de materiais.", category: "Circulação", x: 88, y: 84, width: 19, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Proteção do torno aberta", description: "A proteção da máquina está aberta durante a operação, expondo a zona de corte e projeção.", category: "Máquinas", x: 25, y: 38, width: 34, height: 45, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Óculos deixados na bancada", description: "A proteção ocular deve estar sendo usada antes de entrar na zona de risco, não apenas apoiada na bancada.", category: "EPI", x: 16, y: 70, width: 19, height: 13, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Cavacos transbordando", description: "O recipiente cheio pode espalhar cavacos cortantes no piso; a remoção deve ocorrer com método seguro.", category: "Organização", x: 88, y: 68, width: 22, height: 38, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Ferramenta instável na bancada", description: "Instrumentos de medição e corte precisam ser armazenados de modo a não cair nem cortar pessoas.", category: "Ferramentas", x: 24, y: 82, width: 27, height: 11, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Caixa instável na altura dos ombros", description: "A carga está inclinada e pode cair; materiais devem ser empilhados de forma estável e dentro do limite do rack.", category: "Armazenagem", x: 17, y: 26, width: 24, height: 37, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Palete bloqueando saída", description: "A saída de emergência deve permanecer totalmente livre e acessível.", category: "Emergência", x: 49, y: 42, width: 25, height: 31, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Pedestre na rota de movimentação", description: "A circulação de pedestres deve respeitar a segregação e o controle da rota de equipamentos móveis.", category: "Circulação", x: 64, y: 46, width: 15, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Mangueira no corredor", description: "A mangueira atravessa a circulação e precisa ser recolhida ou conduzida por passagem protegida.", category: "Organização", x: 70, y: 86, width: 55, height: 13, tolerance: 5, shape: "retangulo" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Painel elétrico aberto sem isolamento", description: "Intervenções elétricas exigem controle de acesso, desenergização e sinalização adequada.", category: "Elétrica", x: 13, y: 43, width: 19, height: 48, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Pessoa dentro da área de risco", description: "A pessoa está dentro da zona demarcada próxima à máquina; a área deve ser acessada somente com controle seguro.", category: "Máquinas", x: 83, y: 52, width: 15, height: 37, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Derramamento sem sinalização", description: "O derramamento precisa ser isolado e comunicado antes que alguém escorregue ou espalhe o contaminante.", category: "Químico", x: 42, y: 78, width: 31, height: 22, tolerance: 5, shape: "poligono" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Botão de emergência obstruído", description: "O comando de emergência deve permanecer livre para acionamento imediato.", category: "Emergência", x: 91, y: 67, width: 14, height: 27, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Proteção de máquina parcialmente aberta", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Ferramenta instável na bancada", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Material na rota amarela", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Postura de torção", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Botão de emergência bloqueado", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Óculos fora do rosto", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Palete fora da área demarcada", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-producao-2026", title: "Cabo sem proteção", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Área sem sinalização", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Carga apoiada de forma irregular", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Acesso à área quente sem isolamento", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Cabo atravessando a circulação", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Recipiente de cavacos cheio", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Proteção facial fora de posição", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Carga suspensa inclinada", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Ferramenta na borda da bancada", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Piso molhado sem sinalização", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Passagem parcialmente obstruída", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Ponto de esmagamento", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Recipiente sem identificação", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Intervenção sem bloqueio visível", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Escada mal posicionada", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Ferramenta no piso", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Pano contaminado fora do recipiente", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Óculos não utilizados", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Painel sem isolamento", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Mangueira em área de passagem", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Postura ajoelhada prolongada", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Peça sem apoio", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Acesso obstruído", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Caixa inclinada no rack", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Material bloqueando saída", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Empilhamento acima do limite", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Paleteira atravessada", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Mangueira no piso", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Caixa aberta na passagem", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Carga sem identificação", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Acesso elevado improvisado", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Carrinho fora da área", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Carga instável no piso", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Monitor abaixo da linha dos olhos", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Cadeira sem ajuste", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Cabo atravessando corredor", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Armário com acesso bloqueado", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Caixa pesada acima dos ombros", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Postura inclinada", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Objeto no piso", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Carga apoiada no alto", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Passagem estreitada", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Extintor parcialmente obstruído", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Pedestre na rota da empilhadeira", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carga bloqueando a visão", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Palete instável", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Corredor obstruído", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Sem segregação de rota", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Trabalhador sem colete", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carga fora da área demarcada", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carrinho abandonado", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Faixa de pedestres bloqueada", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carga sem contenção", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
] as const;


export const EXTREME_CDBS_SPOT_ERROR_HOTSPOTS = CDBS_SPOT_ERROR_SCENARIOS.flatMap((scenario) => [
  { scenarioKey: scenario.key, title: "Sinalização parcialmente encoberta", description: "A sinalização de segurança deve permanecer visível e legível para orientar a circulação e a resposta a emergências.", category: "Sinalização", x: 8, y: 14, width: 10, height: 12, tolerance: 2, shape: "retangulo" as const },
  { scenarioKey: scenario.key, title: "Ferramenta apoiada na quina", description: "Ferramentas deixadas na quina podem cair ou atingir pessoas; mantenha-as em superfície estável e organizada.", category: "Organização", x: 27, y: 31, width: 12, height: 10, tolerance: 2, shape: "retangulo" as const },
  { scenarioKey: scenario.key, title: "Mangueira sem suporte", description: "Mangueiras devem ser conduzidas por suporte ou passagem protegida, sem formar laços na área de circulação.", category: "Circulação", x: 46, y: 54, width: 16, height: 9, tolerance: 2, shape: "retangulo" as const },
  { scenarioKey: scenario.key, title: "Recipiente sem tampa", description: "Recipientes de resíduos ou produtos devem permanecer fechados e identificados conforme o risco.", category: "Químico", x: 71, y: 19, width: 10, height: 12, tolerance: 2, shape: "circulo" as const },
  { scenarioKey: scenario.key, title: "Material fora da faixa", description: "Materiais devem permanecer dentro da área demarcada, sem reduzir a passagem nem invadir a rota segura.", category: "5S", x: 86, y: 91, width: 12, height: 8, tolerance: 2, shape: "retangulo" as const },
]);

export const CDBS_EVENT_QUESTIONS = [
  {
    gameType: "quiz_seguranca" as const,
    question: "Na operação CDBS em Osasco, você observa óleo no corredor entre bancadas. Qual é a primeira atitude?",
    optionA: "Desviar e continuar a atividade para não parar a linha",
    optionB: "Parar com segurança, sinalizar/isolar o local e comunicar a condição Red Flag",
    optionC: "Jogar água para levar o óleo até o ralo",
    optionD: "Esperar a limpeza do fim do turno",
    correctOption: "B" as const,
    explanation: "Uma condição insegura deve ser controlada no momento: pare, proteja a área e comunique para correção.",
    theme: "CDBS Osasco • Red Flag",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Antes de intervir em uma máquina de montagem de motores da CDBS, qual requisito não pode ser omitido?",
    optionA: "Apenas apertar o botão de parada local",
    optionB: "Pedir licença ao colega mais próximo e iniciar rapidamente",
    optionC: "Aplicar LOTO, testar energia zero e seguir o procedimento autorizado",
    optionD: "Remover a proteção para visualizar melhor o componente",
    correctOption: "C" as const,
    explanation: "Bloqueio, etiquetagem e teste de energia zero evitam partidas inesperadas e liberação de energia perigosa.",
    theme: "CDBS Osasco • LOTO",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Ao circular pela fábrica CDBS, qual combinação é obrigatória nas áreas operacionais?",
    optionA: "Óculos de segurança, calçado adequado e respeito às faixas e rotas demarcadas",
    optionB: "Somente colete, se houver visita externa",
    optionC: "Usar celular na faixa amarela para registrar a produção",
    optionD: "Passar por baixo de cargas para ganhar tempo",
    correctOption: "A" as const,
    explanation: "EPI e circulação disciplinada protegem o pedestre nos cruzamentos e áreas de montagem.",
    theme: "CDBS Osasco • Circulação e EPI",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Uma saída de emergência da unidade está parcialmente bloqueada por um palete. O que fazer?",
    optionA: "Deixar o palete até a próxima janela logística",
    optionB: "Mover sozinho sem avaliar o peso e sem comunicar",
    optionC: "Comunicar imediatamente, retirar o bloqueio com segurança e manter a rota livre",
    optionD: "Colocar uma caixa menor sobre o palete para sinalizar",
    correctOption: "C" as const,
    explanation: "Rotas de fuga devem permanecer desobstruídas e qualquer bloqueio precisa ser tratado de imediato.",
    theme: "CDBS Osasco • Emergência",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Na montagem CDBS, qual ajuste ajuda a manter uma postura segura durante a atividade?",
    optionA: "Trabalhar sempre curvado para enxergar melhor",
    optionB: "Ajustar altura e alcance, mantendo carga próxima ao corpo",
    optionC: "Girar o tronco com a peça pesada nos braços",
    optionD: "Permanecer parado sem alternar a tarefa",
    correctOption: "B" as const,
    explanation: "Ajuste do posto e carga próxima reduzem esforço excessivo e sobrecarga musculoesquelética.",
    theme: "CDBS Osasco • Postura",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Ao movimentar um componente pesado na CDBS, qual conduta é mais segura?",
    optionA: "Levantar sozinho para ganhar tempo",
    optionB: "Avaliar o peso, usar o recurso de movimentação e pedir apoio quando necessário",
    optionC: "Carregar com a visão bloqueada pela peça",
    optionD: "Torcer o corpo enquanto levanta",
    correctOption: "B" as const,
    explanation: "Planejamento, auxílio mecânico e trabalho em equipe reduzem o risco de lesões e quedas de materiais.",
    theme: "CDBS Osasco • Movimentação",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Por que as pausas e a alternância de tarefas são importantes na rotina de produção?",
    optionA: "Para reduzir a atenção e acelerar movimentos repetitivos",
    optionB: "Para permitir recuperação física e reduzir a exposição contínua ao mesmo esforço",
    optionC: "Para eliminar a necessidade de seguir o padrão operacional",
    optionD: "Para substituir todos os treinamentos de segurança",
    correctOption: "B" as const,
    explanation: "Pausas e alternância planejadas ajudam a controlar fadiga e repetitividade sem abandonar o padrão seguro.",
    theme: "CDBS Osasco • Pausas e Alternância",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Se surgir dor ou desconforto durante uma atividade, qual atitude está alinhada à cultura CDBS?",
    optionA: "Ignorar até terminar o turno",
    optionB: "Comunicar a liderança, interromper com segurança e buscar orientação",
    optionC: "Compensar fazendo força mais rápido",
    optionD: "Trocar de EPI sem comunicar o sintoma",
    correctOption: "B" as const,
    explanation: "A comunicação precoce permite avaliar o posto e evitar agravamento do desconforto.",
    theme: "CDBS Osasco • Saúde Ocupacional",
    difficulty: "facil" as const,
  },
] as const;
