export const INITIAL_SECURITY_QUESTIONS = [
  {
    gameType: "quiz_seguranca" as const,
    question: "Qual é a atitude correta e imediata ao identificar uma condição de risco (Red Flag) na fábrica?",
    optionA: "Substituir as auditorias formais por notificações aplicadas ao final de cada turno",
    optionB: "Parar a atividade, sinalizar/isolar a área se aplicável e comunicar imediatamente o risco",
    optionC: "Gerar métricas administrativas de desvios sem paralisação imediata da atividade",
    optionD: "Priorizar a velocidade da entrega reclassificando riscos moderados como aceitáveis",
    correctOption: "B" as const,
    explanation: "Na cultura Cummins, ao ver um risco você deve parar, comunicar e agir com segurança antes que ocorra um incidente.",
    theme: "Red Flag & Comunicação de Risco",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Antes de realizar manutenção em motores ou linhas automatizadas, qual procedimento de energia zero é obrigatório?",
    optionA: "Acionar o botão de emergência local e manter a chave de comando em posição desligada",
    optionB: "Combinar verbalmente a intervenção rápida com o operador titular do posto",
    optionC: "Bloqueio e Etiquetagem (LOTO - Lockout & Tagout) com teste de energia residual",
    optionD: "Interromper a alimentação pneumática mantendo os circuitos auxiliares sob monitoramento",
    correctOption: "C" as const,
    explanation: "O processo LOTO garante isolamento confiável de todas as fontes de energia perigosa antes da intervenção.",
    theme: "Bloqueio e Etiquetagem",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Ao transitar pelas áreas operacionais e de montagem da fábrica, qual conduta referente a EPIs é obrigatória?",
    optionA: "Usar óculos de segurança com proteção lateral e calçado com biqueira em todas as faixas operacionais",
    optionB: "Óculos com proteção lateral apenas em postos com operação de corte ou solda ativa",
    optionC: "Calçado de segurança e uso livre de smartphone exclusivamente nas faixas amarelas",
    optionD: "Colete reflexivo em substituição aos calçados com biqueira durante deslocamentos rápidos",
    correctOption: "A" as const,
    explanation: "EPIs básicos como calçado de segurança e óculos com proteção lateral são regras fundamentais para circulação fabril.",
    theme: "EPIs",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "O que deve ser verificado antes de utilizar um extintor de incêndio em um princípio de fogo industrial?",
    optionA: "Se o extintor está pintado com tinta brilhante recente",
    optionB: "A classe do fogo (A, B ou C), o manômetro na faixa verde e a desobstrução do acesso",
    optionC: "Se há água na mangueira mesmo sendo quadro elétrico energizado",
    optionD: "Apenas a cor do lacre de plástico",
    correctOption: "B" as const,
    explanation: "A classe do fogo e a pressão no manômetro determinam o agente extintor correto para não agravar o incêndio.",
    theme: "Procedimentos de Emergência",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Qual é o objetivo principal da campanha Red Flag na unidade Cummins?",
    optionA: "Punir operadores que relatam problemas nas linhas de motores",
    optionB: "Interromper e relatar condições ou atos inseguros antes que se transformem em acidentes",
    optionC: "Apenas registrar estatísticas sem ação de correção em chão de fábrica",
    optionD: "Aumentar a velocidade das linhas sacrificando regras operacionais",
    correctOption: "B" as const,
    explanation: "A Red Flag empodera qualquer colaborador a pausar a operação e comunicar riscos para correção preventiva.",
    theme: "Red Flag",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Em relação ao tráfego de empilhadeiras e rebocadores industriais na planta, qual regra de ouro deve ser seguida?",
    optionA: "O pedestre sempre tem a preferência absoluta em cruzamentos cegos sem olhar",
    optionB: "Respeitar as faixas de pedestre pintadas, manter contato visual com o operador e parar nos cruzamentos sinalizados",
    optionC: "Caminhar olhando o celular desde que dentro da faixa amarela",
    optionD: "Subir no garfo da empilhadeira para alcançar peças altas na estante",
    correctOption: "B" as const,
    explanation: "O contato visual e o respeito à sinalização física evitam atropelamentos e colisões com máquinas em manobra.",
    theme: "Sinalização e Circulação",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Qual é a postura ergonômica adequada ao levantar manualmente uma caixa de componentes pesados do chão?",
    optionA: "Manter as pernas retas e curvar a coluna lombar para baixo",
    optionB: "Flexionar os joelhos, manter a carga próxima ao corpo e manter a coluna ereta",
    optionC: "Girar o tronco bruscamente enquanto faz a força de elevação",
    optionD: "Levantar caixas acima de 25 kg sozinho sem solicitar auxílio mecânico",
    correctOption: "B" as const,
    explanation: "Flexionar os joelhos e aproximar a carga do centro de gravidade protege a coluna lombar contra lesões musculoesqueléticas.",
    theme: "Ergonomia",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Quando uma proteção física móvel de máquina (intertravamento) estiver danificada ou desregulada, o que fazer?",
    optionA: "Burlar o sensor com fita para não parar a meta da linha",
    optionB: "Operar com cuidado redobrado sem avisar a manutenção",
    optionC: "Parar a máquina, etiquetar como inoperante e acionar manutenção/segurança",
    optionD: "Remover a proteção para facilitar o acesso às ferramentas",
    correctOption: "C" as const,
    explanation: "Dispositivos de proteção nunca podem ser burlados; falhas exigem paralisação preventiva imediata.",
    theme: "Máquinas e Proteções",
    difficulty: "dificil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Durante o uso de produtos químicos para lavagem ou desengraxe de peças de motor, qual item é indispensável?",
    optionA: "Consultar a FISPQ/FDS e utilizar luvas químicas, óculos adequados e ventilação",
    optionB: "Cheirar o produto de perto para verificar se ainda está ativo",
    optionC: "Armazenar restos em garrafas plásticas de refrigerante sem rótulo",
    optionD: "Misturar solventes diferentes para aumentar a potência de limpeza",
    correctOption: "A" as const,
    explanation: "A Ficha de Dados de Segurança (FISPQ/FDS) orienta o manuseio seguro, EPIs adequados e primeiros socorros.",
    theme: "Riscos Industriais & Químicos",
    difficulty: "dificil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "O que caracteriza o 'Comportamento Seguro' de uma equipe industrial de alto desempenho?",
    optionA: "Cuidar apenas de si mesmo e ignorar se o colega ao lado estiver sem proteção",
    optionB: "Cuidado ativo: cuidar de si, cuidar do colega e aceitar intervenções seguras",
    optionC: "Apressar tarefas ignorando o checklist de pré-operação",
    optionD: "Relatar quase-acidentes apenas se envolver dano financeiro alto",
    correctOption: "B" as const,
    explanation: "O cuidado ativo constrói uma cultura onde todos se sentem responsáveis pelo retorno seguro de todos para casa.",
    theme: "Comportamento Seguro",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Em caso de acionamento do alarme geral de emergência e evacuação na fábrica, qual é o procedimento correto?",
    optionA: "Correr desesperadamente para o estacionamento pegar o carro",
    optionB: "Interromper atividades em segurança, seguir rotas de fuga sinalizadas e ir ao Ponto de Encontro",
    optionC: "Voltar para o vestiário para pegar mochilas e pertences pessoais",
    optionD: "Subir no telhado para filmar a ocorrência com o smartphone",
    correctOption: "B" as const,
    explanation: "Evacuações exigem calma, rotas desobstruídas e contagem de presença no Ponto de Encontro predeterminado.",
    theme: "Procedimentos de Emergência",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Como o programa 5S contribui diretamente para a prevenção de acidentes na manufatura?",
    optionA: "Serve apenas para deixar o piso encerado para visitas de clientes",
    optionB: "Elimina obstáculos nas rotas, previne tropeços, identifica vazamentos rapidamente e organiza ferramentas",
    optionC: "Substitui a necessidade de utilizar equipamentos de proteção individual",
    optionD: "Reduz o tempo de descanso legal dos colaboradores da planta",
    correctOption: "B" as const,
    explanation: "Ambientes limpos e organizados revelam anomalias, eliminam riscos de tropeço/queda e otimizam a segurança.",
    theme: "Segurança Industrial & 5S",
    difficulty: "medio" as const,
  },
];

export const INITIAL_ERGONOMICS_QUESTIONS = Array.from({ length: 12 }, () => ({ gameType: "quiz_ergonomia" as const }));

export const INITIAL_GAME_SETTINGS = [
  {
    gameKey: "quiz_seguranca",
    title: "SIPAT CDBS • Segurança",
    description: "Perguntas sobre segurança, prevenção de acidentes e rotina operacional da unidade Cummins Osasco.",
    active: true,
  },
  {
    gameKey: "quiz_ergonomia",
    title: "SIPAT CDBS • Ergonomia",
    description: "Desafios sobre postura, movimentação, pausas e saúde ocupacional na rotina CDBS.",
    active: true,
  },
  {
    gameKey: "ache_o_erro",
    title: "SIPAT CDBS • Ache o Erro",
    description: "Inspecione cenários de oficina, montagem, fábrica e apoio administrativo para encontrar atos inseguros.",
    active: true,
  },
  {
    gameKey: "organize_a_fabrica",
    title: "SIPAT CDBS • Organize a Fábrica",
    description: "Aplique 5S e organização visual para deixar o ambiente Cummins Osasco mais seguro e eficiente.",
    active: true,
  },
];


export const CDBS_SPOT_ERROR_SCENARIOS = [
  { key: "cdbs-v4-montagem-2026", label: "Fase 1 • Montagem de Motores • Cummins CDBS", image: "/manus-storage/cenario-1-montagem-errors_aa8b276c.png", safeImage: "/manus-storage/cenario-1-montagem-safe-matched_6faf6a51.png" },
  { key: "cdbs-v4-logistica-2026", label: "Fase 2 • Logística e Armazenagem • Cummins CDBS", image: "/manus-storage/cenario-2-logistica-errors_f8938a35.png", safeImage: "/manus-storage/cenario-2-logistica-safe-matched_695956e6.png" },
  { key: "cdbs-v4-manutencao-2026", label: "Fase 3 • Manutenção Industrial e LOTO • Cummins CDBS", image: "/manus-storage/cenario-3-manutencao-errors_c745d3d2.png", safeImage: "/manus-storage/cenario-3-manutencao-safe-matched_61c7691f.png" },
  { key: "cdbs-v4-usinagem-2026", label: "Fase 4 • Usinagem e Metalurgia • Cummins CDBS", image: "/manus-storage/cenario-4-usinagem-errors_e732a0b0.png", safeImage: "/manus-storage/cenario-4-usinagem-safe-matched_26b27f44.png" },
  { key: "cdbs-v4-producao-2026", label: "Fase 5 • Linha de Produção Automatizada • Cummins CDBS", image: "/manus-storage/cenario-5-producao-errors-clean_1ac8716e.png", safeImage: "/manus-storage/cenario-5-producao-safe-matched_a1c3bc6b.png" },
] as const;

export const V4_CDBS_SPOT_ERROR_HOTSPOTS = [
  { scenarioKey: "cdbs-v4-montagem-2026", title: "EPI incompleto no posto de montagem", description: "O trabalhador opera a montagem com as mãos sem luvas de proteção mecânica, deixando a pele exposta a rebarbas, óleo e pontos de prensagem.", hint: "Observe as mãos e o EPI do trabalhador de uniforme azul no lado esquerdo.", category: "EPI", x: 18.0, y: 35.0, width: 12.0, height: 18.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Cabo elétrico na faixa de pedestres", description: "O cabo da ferramenta pneumática/elétrica atravessa a faixa amarela demarcada, gerando alto risco de tropeço e queda.", hint: "Acompanhe a faixa amarela de pedestres no lado esquerdo do chão.", category: "Circulação", x: 27.0, y: 73.0, width: 28.0, height: 22.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Derramamento de óleo sob o suporte", description: "Poça de óleo lubrificante derramada no piso sob o suporte do motor sem contenção, pó absorvente ou sinalização.", hint: "Olhe para o chão logo abaixo do cavalete metálico.", category: "Químico / 5S", x: 46.0, y: 82.0, width: 18.0, height: 16.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Portão da célula robótica aberto", description: "A porta de proteção perimetral amarela da célula robotizada está aberta enquanto o robô está operando.", hint: "Verifique a grade de proteção amarela no fundo da fábrica.", category: "Proteção de Máquinas", x: 33.0, y: 24.0, width: 19.0, height: 30.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Caixas empilhadas instáveis no carrinho", description: "Caixas de papelão empilhadas tortas e acima da altura permitida no carrinho vermelho, com risco iminente de tombamento.", hint: "Observe o empilhamento de caixas no carrinho vermelho móvel.", category: "Armazenagem / Movimentação", x: 63.0, y: 43.0, width: 22.0, height: 18.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Mão desprotegida sem luva de segurança", description: "O operador manuseia engrenagens e peças metálicas pontiagudas com as mãos nuas, sem luvas de proteção mecânica.", hint: "Olhe atentamente para as mãos do operador à direita na bancada.", category: "EPI", x: 78.0, y: 55.0, width: 13.0, height: 16.0, tolerance: 2.0, shape: "circulo" },
  { scenarioKey: "cdbs-v4-montagem-2026", title: "Chave pesada na borda da bancada", description: "Chave fixa grande deixada na beirada da mesa, sujeita a cair nos pés do trabalhador com a vibração da linha.", hint: "Examine a quina da bancada de trabalho no canto direito inferior.", category: "Organização / 5S", x: 86.0, y: 69.0, width: 18.0, height: 14.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Carga alta bloqueando a visão da empilhadeira", description: "Empilhadeira transportando pilha excessiva de pallets que obstrui 100% da linha de visão frontal do operador.", hint: "Olhe para a altura dos pallets nos garfos da empilhadeira laranja.", category: "Movimentação de Cargas", x: 27.0, y: 67.0, width: 25.0, height: 28.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Pallets inclinados em altura no rack", description: "Pilha de pallets torta e instável na última prateleira do porta-pallets, com risco de queda sobre as pessoas.", hint: "Observe o topo da estante azul de armazenamento à direita.", category: "Armazenagem", x: 68.0, y: 18.0, width: 27.0, height: 25.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Líquido escorregadio na faixa de pedestres", description: "Grande poça de óleo/água derramada na faixa demarcada de pedestres, sem cone de aviso ou sinalização de piso molhado.", hint: "Olhe a faixa amarela bem no centro do piso do corredor.", category: "Circulação / 5S", x: 53.0, y: 64.0, width: 22.0, height: 20.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Distração com celular na área operacional", description: "Pedestre caminhando enquanto digita no celular, ignorando o tráfego de empilhadeiras e a poça no chão.", hint: "Veja o que o colaborador que caminha na faixa está segurando.", category: "Comportamento Seguro", x: 44.0, y: 56.0, width: 10.0, height: 24.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Caixa invadindo a rota de emergência", description: "Caixa de carga posicionada junto à porta de emergência, estreitando a aproximação e dificultando a saída rápida.", hint: "Observe a caixa grande junto ao acesso da porta EXIT no lado esquerdo.", category: "Emergência / Rota de Fuga", x: 51.0, y: 40.0, width: 13.0, height: 18.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Escalada insegura na estrutura da estante", description: "Colaborador escalando as travessas do porta-pallets como se fosse uma escada, gerando gravíssimo risco de queda de altura.", hint: "Observe o homem de costas subindo pelas laterais do rack azul.", category: "Trabalho em Altura", x: 85.0, y: 61.0, width: 13.0, height: 26.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-logistica-2026", title: "Fitas plásticas de embalagem soltas no piso", description: "Fitas e filmes plásticos de amarração de carga espalhados pelo chão, com facilidade para enroscar nas pernas.", hint: "Olhe os restos de plástico e fitas brancas jogadas no piso perto do rack.", category: "5S / Organização", x: 72.0, y: 78.0, width: 32.0, height: 22.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Cadeados ausentes na estação LOTO", description: "Caixa vermelha de bloqueio (Lockout Station) aberta com cadeados de segurança faltando e sem controle de chaves.", hint: "Examine a caixa vermelha fixada na parede no canto superior esquerdo.", category: "Bloqueio e Etiquetagem (LOTO)", x: 28.0, y: 23.0, width: 18.0, height: 22.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Etiqueta LOTO jogada no chão", description: "Etiqueta amarela e vermelha 'DANGER LOCKOUT' caída no piso da fábrica, em vez de fixada ao ponto de desenergização.", hint: "Procure uma etiqueta colorida caída no chão perto da máquina da esquerda.", category: "Bloqueio e Etiquetagem (LOTO)", x: 29.0, y: 45.0, width: 13.0, height: 12.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Intervenção em painel elétrico sem luvas isolantes", description: "Eletricista atuando diretamente dentro do painel elétrico energizado com mãos desprotegidas sem luvas dielétricas.", hint: "Observe as mãos do eletricista mexendo nos barramentos do painel aberto.", category: "Segurança Elétrica / NR-10", x: 58.0, y: 39.0, width: 12.0, height: 22.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Chave pesada sobre torno mecânico", description: "Chave ajustável pesada apoiada sobre o torno sem fixação, podendo cair durante a vibração de corte.", hint: "Olhe em cima do torno CNC na parte inferior esquerda.", category: "Ferramentas / 5S", x: 30.0, y: 63.0, width: 16.0, height: 15.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Cabo de alimentação elétrico cruzando passagem", description: "Cabo preto grosso jogado no chão atravessando o corredor sem calha ou rampa protetora para pedestres.", hint: "Acompanhe o cabo preto que sai do painel elétrico e cruza o chão.", category: "Circulação / Risco de Queda", x: 60.0, y: 80.0, width: 32.0, height: 20.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Porta da máquina CNC aberta em operação", description: "Porta de vidro de segurança da máquina CNC totalmente aberta enquanto a ferramenta está em giro.", hint: "Verifique a porta aberta da máquina fresadora azul à direita.", category: "Proteção de Máquinas / NR-12", x: 63.0, y: 56.0, width: 18.0, height: 30.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-manutencao-2026", title: "Vazamento de fluido hidráulico no piso", description: "Poça amarela de óleo hidráulico vazando da base da máquina sem bacia de contenção ou manta absorvente.", hint: "Procure a mancha amarela escorrendo na base da máquina da direita.", category: "Meio Ambiente / Químico", x: 78.0, y: 72.0, width: 24.0, height: 18.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Óculos de proteção pendurados no pescoço", description: "Operador usinando peças com óculos no pescoço em vez de sobre os olhos, sujeito a estilhaços de metal incandescente.", hint: "Olhe o pescoço do operador do torno superior vermelho.", category: "EPI", x: 18.0, y: 27.0, width: 8.0, height: 10.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Capô de proteção do torno aberto", description: "Carenagem vermelha de proteção do torno mecânico totalmente erguida durante o corte com faíscas.", hint: "Observe a proteção vermelha levantada na máquina de usinagem superior.", category: "Proteção de Máquinas / NR-12", x: 43.0, y: 18.0, width: 16.0, height: 24.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Cavacos metálicos transbordando no chão", description: "Caixa azul de cavacos cheia além da borda, espalhando rebarbas cortantes no piso onde os trabalhadores pisam.", hint: "Olhe a caixa azul com aparas de metal no canto inferior esquerdo.", category: "5S / Organização", x: 18.0, y: 77.0, width: 22.0, height: 24.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Ferramentas pontiagudas na borda da mesa", description: "Limas e paquímetro de precisão soltos na extremidade da bancada de metal sem bandeja de segurança.", hint: "Examine a bancada metálica com gavetas vermelhas no centro.", category: "Ferramentas", x: 37.0, y: 73.0, width: 18.0, height: 16.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Fluido de corte derramado na faixa amarela", description: "Grande poça de fluido de corte refrigerante azul escorrendo diretamente sobre a rota amarela de pedestres.", hint: "Procure o líquido azul brilhante derramado sobre a faixa amarela.", category: "Químico / Circulação", x: 57.0, y: 75.0, width: 24.0, height: 22.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Cabelo longo solto próximo a eixos giratórios", description: "Trabalhadora com cabelos longos soltos caminhando muito perto de máquinas rotativas, com risco grave de aprisionamento.", hint: "Observe o cabelo da trabalhadora caminhando no corredor.", category: "Comportamento Seguro / Vestimenta", x: 72.0, y: 58.0, width: 10.0, height: 20.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-usinagem-2026", title: "Mangueira de ar comprimido esticada no piso", description: "Mangueira amarela sob pressão esticada transversalmente sobre a demarcação de tráfego, criando barreira de tropeço.", hint: "Veja a mangueira amarela cruzando o piso próximo aos pés do homem no fundo.", category: "Circulação / Risco de Queda", x: 84.0, y: 75.0, width: 25.0, height: 25.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Porta de vidro da célula robótica aberta", description: "Porta de proteção transparente da cabine do robô aberta enquanto o braço robótico manipula blocos de motor.", hint: "Olhe a porta da cabine de vidro do robô no centro da linha.", category: "Proteção de Máquinas / NR-12", x: 40.0, y: 32.0, width: 18.0, height: 30.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Operadora com óculos na cabeça", description: "A operadora ergueu os óculos de proteção para a cabeça ao conversar ao lado da esteira de montagem.", hint: "Observe a cabeça da operadora de blusa vermelha no canto esquerdo.", category: "EPI", x: 7.0, y: 45.0, width: 10.0, height: 14.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Carrinho azul de peças na faixa de pedestres", description: "Carrinho de componentes estacionado no meio do corredor demarcado em amarelo, bloqueando passagem segura.", hint: "Veja o carrinho azul com peças no centro da faixa amarela.", category: "Circulação / 5S", x: 54.0, y: 72.0, width: 16.0, height: 24.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Engrenagem pesada caída na faixa", description: "Grande coroa de engrenagem metálica caída no meio da rota de circulação sem sinalização.", hint: "Olhe para a peça circular metálica caída no chão sobre a faixa.", category: "Circulação / Risco de Queda", x: 38.0, y: 84.0, width: 15.0, height: 15.0, tolerance: 2.0, shape: "circulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Caixas bloqueando botoeira de emergência", description: "Pilha de caixas de papelão encostada na parede impedindo o alcance imediato do botão de parada de emergência vermelho.", hint: "Examine as caixas empilhadas na parede perto do botão vermelho.", category: "Emergência / NR-12", x: 73.0, y: 34.0, width: 19.0, height: 34.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Postura perigosa debruçado sobre esteira", description: "Operador estica o corpo perigosamente por cima dos roletes em movimento para alcançar um motor preso.", hint: "Observe a postura do trabalhador debruçado sobre a esteira de roletes.", category: "Ergonomia / Ponto de Prensagem", x: 82.0, y: 58.0, width: 20.0, height: 22.0, tolerance: 2.0, shape: "retangulo" },
  { scenarioKey: "cdbs-v4-producao-2026", title: "Carenagem da corrente retirada no chão", description: "Proteção amarela da transmissão por corrente e engrenagem desmontada no piso, deixando partes móveis expostas.", hint: "Olhe a proteção amarela retirada no chão abaixo da esteira.", category: "Proteção de Máquinas / NR-12", x: 80.0, y: 86.0, width: 20.0, height: 20.0, tolerance: 2.0, shape: "retangulo" },
] as const;

export const INITIAL_CDBS_SPOT_ERROR_HOTSPOTS = [
  { scenarioKey: "cdbs-oficina-2026", title: "Óculos levantados durante a ferramenta", description: "O trabalhador está com proteção ocular fora da posição correta durante a atividade; o EPI deve proteger os olhos enquanto houver risco de projeção.", category: "EPI", x: 35, y: 17, width: 18, height: 38, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Cabo atravessando a passagem", description: "O cabo ocupa a rota amarela e pode causar tropeço; deve ser organizado ou protegido.", category: "Circulação", x: 52, y: 75, width: 38, height: 12, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Pano oleoso fora do recipiente", description: "Panos contaminados devem ir para recipiente apropriado, evitando contato e risco de incêndio.", category: "Químico", x: 91, y: 78, width: 15, height: 18, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Ferramenta na borda da bancada", description: "A ferramenta pode cair e atingir alguém; mantenha ferramentas em local estável e organizado.", category: "Organização", x: 16, y: 71, width: 18, height: 10, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Proteção da máquina aberta", description: "A proteção deve permanecer fechada durante a operação para impedir acesso à zona de perigo.", category: "Máquinas", x: 40, y: 35, width: 21, height: 44, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Levantamento com postura inadequada", description: "A carga deve ser aproximada do corpo, com joelhos flexionados e sem torção da coluna.", category: "Ergonomia", x: 51, y: 59, width: 18, height: 34, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Carga sem contenção no carrinho", description: "Componentes devem estar apoiados e contidos para não cair durante a movimentação.", category: "Movimentação", x: 73, y: 43, width: 20, height: 25, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Material invadindo a faixa", description: "A rota de pedestres deve permanecer livre e claramente separada das áreas de materiais.", category: "Circulação", x: 88, y: 84, width: 19, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Proteção do torno aberta", description: "A proteção da máquina está aberta durante a operação, expondo a zona de corte e projeção.", category: "Máquinas", x: 25, y: 38, width: 34, height: 45, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Óculos deixados na bancada", description: "A proteção ocular deve estar sendo usada antes de entrar na zona de risco, não apenas apoiada na bancada.", category: "EPI", x: 16, y: 70, width: 19, height: 13, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Cavacos transbordando", description: "O recipiente cheio pode espalhar cavacos cortantes no piso; a remoção deve ocorrer com método seguro.", category: "Organização", x: 88, y: 68, width: 22, height: 38, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Ferramenta instável na bancada", description: "Instrumentos de medição e corte precisam ser armazenados de modo a não cair nem cortar pessoas.", category: "Ferramentas", x: 24, y: 82, width: 27, height: 11, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Caixa instável na altura dos ombros", description: "A carga está inclinada e pode cair; materiais devem ser empilhados de forma estável e dentro do limite do rack.", category: "Armazenagem", x: 17, y: 26, width: 24, height: 37, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Palete bloqueando saída", description: "A saída de emergência deve permanecer totalmente livre e acessível.", category: "Emergência", x: 49, y: 42, width: 25, height: 31, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Pedestre na rota de movimentação", description: "A circulação de pedestres deve respeitar a segregação e o controle da rota de equipamentos móveis.", category: "Circulação", x: 64, y: 46, width: 15, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Mangueira no corredor", description: "A mangueira atravessa a circulação e precisa ser recolhida ou conduzida por passagem protegida.", category: "Organização", x: 70, y: 86, width: 55, height: 13, tolerance: 5, shape: "retangulo" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Painel elétrico aberto sem isolamento", description: "Intervenções elétricas exigem controle de acesso, desenergização e sinalização adequada.", category: "Elétrica", x: 13, y: 43, width: 19, height: 48, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Pessoa dentro da área de risco", description: "A pessoa está dentro da zona demarcada próxima à máquina; a área deve ser acessada somente com controle seguro.", category: "Máquinas", x: 83, y: 52, width: 15, height: 37, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Derramamento sem sinalização", description: "O derramamento precisa ser isolado e comunicado antes que alguém escorregue ou espalhe o contaminante.", category: "Químico", x: 42, y: 78, width: 31, height: 22, tolerance: 5, shape: "poligono" },
  { scenarioKey: "cdbs-maquinas-2026", title: "Botão de emergência obstruído", description: "O comando de emergência deve permanecer livre para acionamento imediato.", category: "Emergência", x: 91, y: 67, width: 14, height: 27, tolerance: 3, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-oficina-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-montagem-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-usinagem-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Faixa obstruída por material", description: "A rota demarcada deve permanecer livre para circulação segura.", category: "Circulação", x: 12, y: 48, width: 18, height: 15, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Recipiente sem identificação", description: "Recipientes precisam estar identificados antes do uso ou armazenamento.", category: "Químico", x: 92, y: 42, width: 10, height: 20, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Acesso de emergência bloqueado", description: "Equipamentos e saídas de emergência devem ficar sempre acessíveis.", category: "Emergência", x: 45, y: 18, width: 18, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Postura fora do padrão", description: "A tarefa deve ser ajustada para reduzir sobrecarga e manter postura neutra.", category: "Ergonomia", x: 61, y: 50, width: 16, height: 30, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Cabo sem proteção", description: "Cabos próximos à passagem devem ser protegidos e organizados.", category: "Elétrica", x: 37, y: 88, width: 34, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-logistica-2026", title: "Carga instável", description: "Materiais precisam de apoio estável e contenção contra quedas.", category: "Armazenagem", x: 76, y: 24, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Proteção de máquina parcialmente aberta", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Ferramenta instável na bancada", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Material na rota amarela", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Postura de torção", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Botão de emergência bloqueado", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Óculos fora do rosto", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Palete fora da área demarcada", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-producao-2026", title: "Cabo sem proteção", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Área sem sinalização", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-producao-2026", title: "Carga apoiada de forma irregular", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Acesso à área quente sem isolamento", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Cabo atravessando a circulação", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Recipiente de cavacos cheio", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Proteção facial fora de posição", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Carga suspensa inclinada", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Ferramenta na borda da bancada", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Piso molhado sem sinalização", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Passagem parcialmente obstruída", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Ponto de esmagamento", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-metalurgia-2026", title: "Recipiente sem identificação", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Intervenção sem bloqueio visível", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Escada mal posicionada", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Ferramenta no piso", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Pano contaminado fora do recipiente", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Óculos não utilizados", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Painel sem isolamento", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Mangueira em área de passagem", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Postura ajoelhada prolongada", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Peça sem apoio", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-manutencao-2026", title: "Acesso obstruído", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Caixa inclinada no rack", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Material bloqueando saída", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Empilhamento acima do limite", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Paleteira atravessada", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Mangueira no piso", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Caixa aberta na passagem", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Carga sem identificação", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Acesso elevado improvisado", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Carrinho fora da área", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-almoxarifado-2026", title: "Carga instável no piso", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Monitor abaixo da linha dos olhos", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Cadeira sem ajuste", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Cabo atravessando corredor", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Armário com acesso bloqueado", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Caixa pesada acima dos ombros", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Postura inclinada", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Objeto no piso", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Carga apoiada no alto", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Passagem estreitada", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-administrativa-2026", title: "Extintor parcialmente obstruído", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Pedestre na rota da empilhadeira", description: "A condição deve ser corrigida antes de continuar a atividade, mantendo a proteção e o controle do risco.", category: "Máquinas", x: 18, y: 34, width: 22, height: 36, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carga bloqueando a visão", description: "Ferramentas e materiais precisam permanecer estáveis e organizados para não causar queda ou impacto.", category: "Organização", x: 15, y: 70, width: 24, height: 14, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Palete instável", description: "A rota de circulação deve permanecer livre, sinalizada e separada das áreas de risco.", category: "Circulação", x: 51, y: 66, width: 19, height: 22, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Corredor obstruído", description: "A tarefa deve ser ajustada para manter postura neutra e reduzir sobrecarga musculoesquelética.", category: "Ergonomia", x: 79, y: 45, width: 16, height: 34, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Sem segregação de rota", description: "Equipamentos e rotas de emergência precisam estar livres e acessíveis para resposta imediata.", category: "Emergência", x: 94, y: 72, width: 10, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Trabalhador sem colete", description: "O EPI adequado deve ser usado corretamente antes de entrar na zona de exposição.", category: "EPI", x: 80, y: 24, width: 12, height: 14, tolerance: 4, shape: "circulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carga fora da área demarcada", description: "Cargas devem ficar estáveis, contidas e dentro das áreas e alturas definidas.", category: "Armazenagem", x: 58, y: 87, width: 22, height: 13, tolerance: 4, shape: "poligono" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carrinho abandonado", description: "Cabos e fontes de energia exigem proteção, organização e controle antes da intervenção.", category: "Elétrica", x: 70, y: 82, width: 32, height: 8, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Faixa de pedestres bloqueada", description: "A área deve ter isolamento e comunicação visível para evitar exposição de outras pessoas.", category: "Sinalização", x: 40, y: 25, width: 13, height: 18, tolerance: 4, shape: "retangulo" },
  { scenarioKey: "cdbs-movimentacao-2026", title: "Carga sem contenção", description: "A movimentação deve ser planejada, com carga estável e pessoas fora da linha de perigo.", category: "Movimentação", x: 67, y: 62, width: 18, height: 17, tolerance: 4, shape: "retangulo" },
] as const;


export const EXTREME_CDBS_SPOT_ERROR_HOTSPOTS = CDBS_SPOT_ERROR_SCENARIOS.flatMap((scenario) => [
  { scenarioKey: scenario.key, title: "Sinalização parcialmente encoberta", description: "A sinalização de segurança deve permanecer visível e legível para orientar a circulação e a resposta a emergências.", category: "Sinalização", x: 8, y: 14, width: 10, height: 12, tolerance: 2, shape: "retangulo" as const },
  { scenarioKey: scenario.key, title: "Ferramenta apoiada na quina", description: "Ferramentas deixadas na quina podem cair ou atingir pessoas; mantenha-as em superfície estável e organizada.", category: "Organização", x: 27, y: 31, width: 12, height: 10, tolerance: 2, shape: "retangulo" as const },
  { scenarioKey: scenario.key, title: "Mangueira sem suporte", description: "Mangueiras devem ser conduzidas por suporte ou passagem protegida, sem formar laços na área de circulação.", category: "Circulação", x: 46, y: 54, width: 16, height: 9, tolerance: 2, shape: "retangulo" as const },
  { scenarioKey: scenario.key, title: "Recipiente sem tampa", description: "Recipientes de resíduos ou produtos devem permanecer fechados e identificados conforme o risco.", category: "Químico", x: 71, y: 19, width: 10, height: 12, tolerance: 2, shape: "circulo" as const },
  { scenarioKey: scenario.key, title: "Material fora da faixa", description: "Materiais devem permanecer dentro da área demarcada, sem reduzir a passagem nem invadir a rota segura.", category: "5S", x: 86, y: 91, width: 12, height: 8, tolerance: 2, shape: "retangulo" as const },
]);

export const CDBS_EVENT_QUESTIONS = [
  {
    gameType: "quiz_seguranca" as const,
    question: "Na operação CDBS em Osasco, você observa óleo no corredor entre bancadas. Qual é a primeira atitude?",
    optionA: "Desviar e continuar a atividade para não parar a linha",
    optionB: "Parar com segurança, sinalizar/isolar o local e comunicar a condição Red Flag",
    optionC: "Jogar água para levar o óleo até o ralo",
    optionD: "Esperar a limpeza do fim do turno",
    correctOption: "B" as const,
    explanation: "Uma condição insegura deve ser controlada no momento: pare, proteja a área e comunique para correção.",
    theme: "CDBS Osasco • Red Flag",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Antes de intervir em uma máquina de montagem de motores da CDBS, qual requisito não pode ser omitido?",
    optionA: "Apenas apertar o botão de parada local",
    optionB: "Pedir licença ao colega mais próximo e iniciar rapidamente",
    optionC: "Aplicar LOTO, testar energia zero e seguir o procedimento autorizado",
    optionD: "Remover a proteção para visualizar melhor o componente",
    correctOption: "C" as const,
    explanation: "Bloqueio, etiquetagem e teste de energia zero evitam partidas inesperadas e liberação de energia perigosa.",
    theme: "CDBS Osasco • LOTO",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Ao circular pela fábrica CDBS, qual combinação é obrigatória nas áreas operacionais?",
    optionA: "Óculos de segurança, calçado adequado e respeito às faixas e rotas demarcadas",
    optionB: "Somente colete, se houver visita externa",
    optionC: "Usar celular na faixa amarela para registrar a produção",
    optionD: "Passar por baixo de cargas para ganhar tempo",
    correctOption: "A" as const,
    explanation: "EPI e circulação disciplinada protegem o pedestre nos cruzamentos e áreas de montagem.",
    theme: "CDBS Osasco • Circulação e EPI",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_seguranca" as const,
    question: "Uma saída de emergência da unidade está parcialmente bloqueada por um palete. O que fazer?",
    optionA: "Deixar o palete até a próxima janela logística",
    optionB: "Mover sozinho sem avaliar o peso e sem comunicar",
    optionC: "Comunicar imediatamente, retirar o bloqueio com segurança e manter a rota livre",
    optionD: "Colocar uma caixa menor sobre o palete para sinalizar",
    correctOption: "C" as const,
    explanation: "Rotas de fuga devem permanecer desobstruídas e qualquer bloqueio precisa ser tratado de imediato.",
    theme: "CDBS Osasco • Emergência",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Na montagem CDBS, qual ajuste ajuda a manter uma postura segura durante a atividade?",
    optionA: "Trabalhar sempre curvado para enxergar melhor",
    optionB: "Ajustar altura e alcance, mantendo carga próxima ao corpo",
    optionC: "Girar o tronco com a peça pesada nos braços",
    optionD: "Permanecer parado sem alternar a tarefa",
    correctOption: "B" as const,
    explanation: "Ajuste do posto e carga próxima reduzem esforço excessivo e sobrecarga musculoesquelética.",
    theme: "CDBS Osasco • Postura",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Ao movimentar um componente pesado na CDBS, qual conduta é mais segura?",
    optionA: "Levantar sozinho para ganhar tempo",
    optionB: "Avaliar o peso, usar o recurso de movimentação e pedir apoio quando necessário",
    optionC: "Carregar com a visão bloqueada pela peça",
    optionD: "Torcer o corpo enquanto levanta",
    correctOption: "B" as const,
    explanation: "Planejamento, auxílio mecânico e trabalho em equipe reduzem o risco de lesões e quedas de materiais.",
    theme: "CDBS Osasco • Movimentação",
    difficulty: "facil" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Por que as pausas e a alternância de tarefas são importantes na rotina de produção?",
    optionA: "Para reduzir a atenção e acelerar movimentos repetitivos",
    optionB: "Para permitir recuperação física e reduzir a exposição contínua ao mesmo esforço",
    optionC: "Para eliminar a necessidade de seguir o padrão operacional",
    optionD: "Para substituir todos os treinamentos de segurança",
    correctOption: "B" as const,
    explanation: "Pausas e alternância planejadas ajudam a controlar fadiga e repetitividade sem abandonar o padrão seguro.",
    theme: "CDBS Osasco • Pausas e Alternância",
    difficulty: "medio" as const,
  },
  {
    gameType: "quiz_ergonomia" as const,
    question: "Se surgir dor ou desconforto durante uma atividade, qual atitude está alinhada à cultura CDBS?",
    optionA: "Ignorar até terminar o turno",
    optionB: "Comunicar a liderança, interromper com segurança e buscar orientação",
    optionC: "Compensar fazendo força mais rápido",
    optionD: "Trocar de EPI sem comunicar o sintoma",
    correctOption: "B" as const,
    explanation: "A comunicação precoce permite avaliar o posto e evitar agravamento do desconforto.",
    theme: "CDBS Osasco • Saúde Ocupacional",
    difficulty: "facil" as const,
  },
] as const;
